### ISSUE TITLE
範例「資訊儀表板」左列有可能因為畫面長度增加所以下面沒有塗黑

### ISSUE THREAD

**Issue by PichuChen** [teacat/tocas#1034]
![スクリーンショット 2024-04-22 朝10 23 53](https://github.com/teacat/tocas/assets/600238/26c88746-6447-4b08-a6b9-4d0730383753)

建議加上 `min-height: fit-content;`
https://github.com/teacat/tocas/blob/0d9b81af9888bc3d85bfe99dc078688eff3fe2eb/src/app-layout.css#L13

**Comment by YamiOdymel** [comment]
修復這個問題的方法是右邊的那欄加上 is-scrollable，
這樣就能在右邊內容超出畫面時，使右邊的內容捲動，而不會擠壓整個畫面
Fixed in 5.0 docs

**Comment by PichuChen** [comment]
> 修復這個問題的方法是右邊的那欄加上 is-scrollable， 這樣就能在右邊內容超出畫面時，使右邊的內容捲動，而不會擠壓整個畫面 Fixed in 5.0 docs

4.0.2 加在 menu 或是外面都沒有效果
