### ISSUE TITLE
IOS 16 dialog 顯示異常

### ISSUE THREAD

**Issue by Alpaca0x0** [teacat/tocas#1064]
`dialog` 元素在 `IOS 15.4` 以上支援，但 TocasUI 的 `ts-dialog` 實測在 `IOS 16` 的裝置上，使用 safari、chrome 均無法正常顯示。

**Comment by YamiOdymel** [comment]
我在 iPadOS 18 & Chrome 使用是正常的，
無法正常顯示是什麼意思？目前沒有 `.ts-dialog` 元素，只有 `<dialog class="ts-modal">`

![IMG_0052](https://github.com/user-attachments/assets/2e40a56e-950c-4f42-bdfa-9bc853ee83f6)

**Comment by Alpaca0x0** [comment]
抱歉筆誤，更正是`ts-modal`沒錯。
偶然在 IOS 16 的裝置上瀏覽網頁，發現`<dialog class="ts-modal">`無法被顯示，但測試之後發現原生的`<dialog>`卻可以正常運作。

p.s. 在 IOS 18 測試是正常運作的，只有 IOS 16 以下，不論是 safari 或 chrome 都無法顯示。

![模擬器截圖](https://github.com/user-attachments/assets/082520cb-373d-4aad-ab90-7f659c915ca9)

**Comment by YamiOdymel** [comment]
我覺得有可能是 iOS 16 不支援 `:popover-open`
而 `dialog.ts-modal[open]` 跟這個 Selector 寫在一起，導致瀏覽器不認這個樣式

![image](https://github.com/user-attachments/assets/21913dca-b486-4f30-a2c7-5e02eef666c4)

試試看在 style 新增下列樣式，是不是能解決問題？

```css
dialog.ts-modal[open] {
    display: flex;
}
```

但新的 Chrome 已經支援這個樣式了，
難道卡在某個 iOS 的版本，也會影響 Chrome 支援的樣式嗎

**Comment by Alpaca0x0** [comment]
加上該 style 後可以正常運作了！

這部分不太清楚，但測試的裝置有 `iPhone 12 (IOS 16)`、`iPhone 15 (IOS 18)`、`iPhone 16 (IOS 18)`，以及上古神獸 `iPad mini MD540TA/A (IOS 9.3.6)`。

發現只有 IOS 16 以下才出現這個問題，目前已經解決，感謝您。

**Comment by Alpaca0x0** [comment]
Bug 似乎仍然存在，目前我使用 Tocas 5.0.1 版本，但 dialog 物件無法在 iPhone 上顯示。

**Comment by YamiOdymel** [comment]
他 Closed 是因為在未來（5.0.2）修好了，但還沒發布

**Comment by Alpaca0x0** [comment]
了解，感謝您。
