### ISSUE TITLE
[Feature request] Wrapper

### ISSUE THREAD

**Issue by toby3d** [teacat/tocas#115]
How about adding classes to support the vertical alignment of the center? At least it should be a class for parents (zone for alignment) and the class of an element (block, which must be located in the center of a parent). :relaxed: 

```
<div class="vertical-wrapper">
  <div class="vertical narrow container"> // Or use: style="width: 100%;"
    <h5>Title</h5>
    <p>SampleText SampleText SampleText SampleText...</p>
    <a class="ts button">Click me!</a> <a class="ts button">And me!</a>
  </div>
</div>
```

See [examples here](http://materializecss.com/helpers.html).

**Comment by YamiOdymel** [comment]
I'm still considering this, because I don't like to put the helper classes all over the website,

which also makes me **_gave up_** the feature: [Add `.unselectable` to prevent user select the text](https://github.com/TeaMeow/TocasUI/issues/90)

this can be done and add to your own website style by using ([**online example**](https://jsfiddle.net/kwyu78nd/)):

``` css
[class*="vertical align wrapper"]
{
    display         : flex;
    align-items     : center;
    justify-content : center;
}
```

and here's your HTML:

``` html
<div class="vertical align wrapper">
    <div class="container">
        <h1>Hello, world!</h1>
        <small>Hello, </small><small>world!</small>
        <h1>Hello, world!</h1>
    </div>
</div>
```

**Comment by toby3d** [comment]
@YamiOdymel If possible, I will leave this issue open. Maybe someone else needed a similar feature.
Or is it absolutely will not be included in the framework?

**Comment by YamiOdymel** [comment]
This is absolutely a great feature but **you'll need an extra `.container` in the `.wrapper`** which makes me headache _(I generally don't like wrapper things)_,

otherwise I might add the feature to `.ts.container`, 

I'll leave it open for now, maybe there will be some new ideas popup 😊
