### ISSUE TITLE
請求新增圖片hover效果

### ISSUE THREAD

**Issue by jeffry1829** [teacat/tocas#121]
當滑鼠在圖片上的時候能夠讓cursor變成 手指頭 或是圖片能夠抬升

**Comment by YamiOdymel** [comment]
Note: `.ts.link.image`, `<a>.ts.image</a>`

**Comment by YamiOdymel** [comment]
完成於 @6ec5a3bde5ffcec7ee2268f41e51654f3cfa61be 會在 Tocas UI 2.1 釋出。
