### ISSUE TITLE
[T2] Toast & Snackbar

### ISSUE THREAD

**Issue by toby3d** [teacat/tocas#129]
Make Tocas great again! :tada:

**Comment by YamiOdymel** [comment]
I will leave this issue for Notifications only because tooltips has been mentioned in #123 :D

and I might reopen #25 for Modal element.

![2016-11-15 8 09 55](https://cloud.githubusercontent.com/assets/7308718/20305227/7eabd020-ab6f-11e6-87ba-687ac3e7001c.png)

**Comment by YamiOdymel** [comment]
Not implemented yet, just a note for myself.

---

![2016-11-19 4 48 03](https://cloud.githubusercontent.com/assets/7308718/20446185/660b308c-ae13-11e6-8704-6a43c106e2a2.png)
![2016-11-19 4 47 56](https://cloud.githubusercontent.com/assets/7308718/20446184/65f3406c-ae13-11e6-9367-b9194b6c9b02.png)

http://www.kule.tw/doc-components-notices.html

``` html
<div class="ts message"></div>

<script>
    ts('.ts.message').notification("Wow", {positive: true})
</script>
```

**Comment by YamiOdymel** [comment]
I might **not** implement this function because this **relies JavaScript heavily** (which is I'm trying to avoid), this should be done at the application-side.

**I will still add some notification-like styles**, and leaving this question as opening until I finished all of the things that relate to notification.

**Comment by YamiOdymel** [comment]
![ezgif-1-1fc7ac0860](https://cloud.githubusercontent.com/assets/7308718/25312716/ca3acc16-2852-11e7-86f5-24ac032ea7c6.gif)

The Snackbar JavaScript function has been added in 2.3, the issue will be closed tonight,

for notification-like messages, check out #265.

---

NOTICE: The Snackbar **cannot** be stacked based on the Google Material Design.
