### ISSUE TITLE
希望 .ts.card 的自動層疊和瀑布流可以一起套用

### ISSUE THREAD

**Issue by gnehs** [teacat/tocas#196]
慘慘QQ
![image 001](https://cloud.githubusercontent.com/assets/16719720/23099919/3fe89ee8-f6ad-11e6-886c-a69e7e23c97c.png)

**Comment by YamiOdymel** [comment]
我記得這部分是沒問題的，你是怎麼寫的貼出來讓我看看？

**Comment by gnehs** [comment]
```
<div class="ts stackable three waterfall cards">
...
</div>
```

**Comment by YamiOdymel** [comment]
好的，是 Bug 沒錯。今天會修復。


`.ts.waterfall.cards.three` 會覆蓋在行動裝置下的 `.ts.stackable.waterfall.cards`

![screen shot 2017-02-19 at 5 15 01 pm](https://cloud.githubusercontent.com/assets/7308718/23101053/f8aab65a-f6c6-11e6-9029-e85fd983d5b7.png)
