### ISSUE TITLE
引言裡的引言

### ISSUE THREAD

**Issue by gnehs** [teacat/tocas#197]
![image 005](https://cloud.githubusercontent.com/assets/16719720/23330699/83d438d8-fb8f-11e6-803d-faa010425914.png)
![image 004](https://cloud.githubusercontent.com/assets/16719720/23330691/4e612328-fb8f-11e6-9dfa-836509670077.png)
顏色會因 ```opacity: .7;```的關係變淡
而且 ```ts secondary quote``` 的  Margin 有點問題

**Comment by YamiOdymel** [comment]
顏色問題修正了，最近會釋出新版本 2.2.2。至於 Margin 問題我這裡是沒有，結構如下。

![screen shot 2017-03-18 at 6 23 24 pm](https://cloud.githubusercontent.com/assets/7308718/24071247/54887c18-0c08-11e7-82ad-c9c56e3da228.png)


```html
<blockquote class="ts secondary quote">
    <p>臺灣是位於亞洲東部、太平洋西北側的島嶼，地處琉球群島與菲律賓群島之間，西隔臺灣海峽與歐亞大陸相望；面積約3.6萬平方公里， 為世界第38大島嶼，其中7成為山地與丘陵，平原則主要集中於西部沿海，地形海拔變化大。由於地處熱帶及亞熱帶氣候區之交界，自然景觀與生態系資源相當豐富而多元。</p>
    <blockquote class="ts secondary quote">
        <p>臺灣是位於亞洲東部、太平洋西北側的島嶼，地處琉球群島與菲律賓群島之間，西隔臺灣海峽與歐亞大陸相望；面積約3.6萬平方公里， 為世界第38大島嶼，其中7成為山地與丘陵，平原則主要集中於西部沿海，地形海拔變化大。由於地處熱帶及亞熱帶氣候區之交界，自然景觀與生態系資源相當豐富而多元。</p>
        <blockquote class="ts secondary quote">
            <p>臺灣是位於亞洲東部、太平洋西北側的島嶼，地處琉球群島與菲律賓群島之間，西隔臺灣海峽與歐亞大陸相望；面積約3.6萬平方公里， 為世界第38大島嶼，其中7成為山地與丘陵，平原則主要集中於西部沿海，地形海拔變化大。由於地處熱帶及亞熱帶氣候區之交界，自然景觀與生態系資源相當豐富而多元。</p>
            <cite>維基百科</cite>
        </blockquote>
        <cite>維基百科</cite>
    </blockquote>
    <cite>維基百科</cite>
</blockquote>
```
