### ISSUE TITLE
當 List 出現 label 時，文字排版會偏上

### ISSUE THREAD

**Issue by gnehs** [teacat/tocas#199]
![image 002](https://cloud.githubusercontent.com/assets/16719720/23339311/97e23d72-fc5a-11e6-9454-17bc7e4a50c5.png)

```html
<div class="ts list relaxed selection">
    <a class="item" href="http://cdn.gnehs.com.tw/cdn/spring/">好的
        <div class="right floated content">
            <div class="ts mini compact label">
                2
            </div>
        </div>
    </a>
</div>
```

**Comment by YamiOdymel** [comment]
我這邊測試的時候沒有發現問題，這個問題還存在嗎？

![screen shot 2017-03-18 at 2 21 37 am](https://cloud.githubusercontent.com/assets/7308718/24057222/a51d0f9a-0b81-11e7-9833-72d205239c70.png)

---

**這個問題先關閉，如果還在的話重新打開就可以了。**

**Comment by gnehs** [comment]
![image 001](https://cloud.githubusercontent.com/assets/16719720/24072184/03cca554-0c1e-11e7-9866-515ccd6d365a.png)
問題好像還在，我的 Tocas UI 是3/16 下載的，我再重下載試試

**Comment by gnehs** [comment]
![image 002](https://cloud.githubusercontent.com/assets/16719720/24072252/4787fae0-0c1f-11e7-8530-a735fa8e8ddc.png)
Cent Browser 2.4.2.19 

![image 003](https://cloud.githubusercontent.com/assets/16719720/24072266/641c5fde-0c1f-11e7-9e03-253fa6ea21cd.png)
Opera 43.0.2442.1144

問題仍在

**Comment by YamiOdymel** [comment]
我沒做修改，瀏覽器爬帶吧

**Comment by gnehs** [comment]
也許是我的問題吧，等新版出來再試試吧

**Comment by YamiOdymel** [comment]
好，看來是我動了什麼設定讓瀏覽器文字可以小於基準值，所以沒有這個問題，

現在發現這個問題是確實存在的了，我現在來想想怎麼修它。

**Comment by YamiOdymel** [comment]
嘗試使用 `ts middle aligned list`。
