### ISSUE TITLE
選單應增加置頂功能

### ISSUE THREAD

**Issue by itshenrywu** [teacat/tocas#20]

**Comment by YamiOdymel** [comment]
求實際範例，

因為你可以透過 `.fluid` 來讓選單成為 100% 寬的選單

然後再設定 `position: fixed`

**Comment by itshenrywu** [comment]
除了新增position:fixed，
還要把border-radius設為0

可以直接新增一個class讓他可以直接置頂？

**Comment by YamiOdymel** [comment]
.fluid 的時候應該沒有圓角吧？

**Comment by YamiOdymel** [comment]
欸等等好像有圓角（？

**Comment by YamiOdymel** [comment]
直接置頂可能會有

**Comment by YamiOdymel** [comment]
@ombwp 不對欸，我發現 `.fluid` 確實會自動移除圓角

**Comment by itshenrywu** [comment]
所以我還是要自己加：
position:fixed;
top:0;
right:0;
就是了😐😐😐

**Comment by YamiOdymel** [comment]
吼好啦ww
