### ISSUE TITLE
.ts.big.heading.slate 裡的按鈕擺上圖示後變得無比巨大

### ISSUE THREAD

**Issue by gnehs** [teacat/tocas#208]
![image 004](https://cloud.githubusercontent.com/assets/16719720/24042369/9dc622b6-0b4c-11e7-9fda-c3312231162e.png)
前
![image 001](https://cloud.githubusercontent.com/assets/16719720/24042372/9f0318f0-0b4c-11e7-8ce9-eed74e3731fd.png)
後

```
<div class="ts big heading slate">
  <span class="header">我被CIA監控了嗎?</span>
  <span class="description">點擊下面按鈕來檢查</span>
  <div class="action">
    <button class="ts labeled icon primary button">
      <i class="doctor icon"></i>
     檢查
    </button>
  </div>
</div>
```

**Comment by YamiOdymel** [comment]
太大啦wwww

**Comment by gnehs** [comment]
![image 002](https://cloud.githubusercontent.com/assets/16719720/24043067/adccfd3a-0b4f-11e7-9ea1-45742c1e8a54.png)
不只 .big.heading ，正常的也是，而且視覺觀感更大
