### ISSUE TITLE
官方說明文件裡的 Bttn CSS 失連

### ISSUE THREAD

**Issue by gnehs** [teacat/tocas#209]
![image 001](https://cloud.githubusercontent.com/assets/16719720/24042924/26487128-0b4f-11e7-8b93-f8b21ed8ccb9.png)
就失連，這樣

**Comment by gnehs** [comment]
啊幹，是我的問題

**Comment by YamiOdymel** [comment]
笑死

**Comment by YamiOdymel** [comment]
其實如果這方面真的失連的話，你可以考慮 Fork 一份 Tocas UI 然後修正他的連結，接著發送 Pull Request 回來合併，這樣的話你就可以出現在貢獻者清單上面，感覺比較熱鬧一點 <3
