### ISSUE TITLE
[VERSION] v1.1 改變紀錄

### ISSUE THREAD

**Issue by YamiOdymel** [teacat/tocas#21]
1. 修正 `x column` 跟 Grid 在一起用時無法採用 `stackable`。
2. 將 `transparent input` 正名為 `basic input`。
3. 新增 Tocas JS。
4. 新增 Sidebar。
5. Grid 修正上下沒有補間邊距。
6. 引用 Animate.css。
7. 最佳問題員工: ombwp http://omwu.me

**Comment by itshenrywu** [comment]
最後一句是三小ww

**Comment by YamiOdymel** [comment]
@ombwp 我只是記得要在 Release 的時候提及你而已www
