### ISSUE TITLE
icon 跑出去惹

### ISSUE THREAD

**Issue by gnehs** [teacat/tocas#224]
![image 001](https://cloud.githubusercontent.com/assets/16719720/24321878/665adcf8-1192-11e7-94ca-9e6895a86795.png)

```html
<div class="ts card">
    <div class="content">
        <div class="header">台北市</div>
        <div class="description">15℃</div>
        <div class="symbol">
            <i class="cloud icon"></i>
        </div>
    </div>
</div>
```

**Comment by YamiOdymel** [comment]
`symbol` 要放在 `content` **外面**。

![screen shot 2017-03-25 at 7 57 07 pm](https://cloud.githubusercontent.com/assets/7308718/24321972/41cdc320-1195-11e7-87e9-3260d56ea951.png)

**Comment by gnehs** [comment]
Sorry 沒看清楚範例 QQ

**Comment by YamiOdymel** [comment]
以前確實是這樣用，後來不方便設計所以把它從 content 搬出來了
