### ISSUE TITLE
ts input "action"和 "labeled"無法並用

### ISSUE THREAD

**Issue by gnehs** [teacat/tocas#225]
![image 002](https://cloud.githubusercontent.com/assets/16719720/24362328/0132867e-133f-11e7-9236-9ef5807aa419.png)

```html
<div class="ts action labeled input">
	<div class="ts label">
		 縣/市鄉/鎮
	</div>
	<input type="text" id="input" placeholder="查詢城市" value="台北">
	<div class="ts label">
		 縣/市鄉/鎮
	</div>
	<button class="ts right labeled icon button" onclick="SearchWeather()">
		<i class="search link icon"></i>
		查詢城市
	</button>
</div>
```

**Comment by YamiOdymel** [comment]
試著使用 `right labled` 像這樣：

![screen shot 2017-03-28 at 12 37 20 am](https://cloud.githubusercontent.com/assets/7308718/24367314/c5191904-134e-11e7-9cdc-aeaf69cb3aa3.png)

```html
<div class="ts right labeled action input">
    <div class="ts label">$</div>
    <input type="text" placeholder="Amount">
    <div class="ts label">.00</div>
    <button class="ts positive button">Hello</button>
</div>
```

**Comment by gnehs** [comment]
解決了，但是不太直覺......

**Comment by YamiOdymel** [comment]
畢竟 CSS 沒辦法透過 If 條件式判斷後面是否有元素，所以只能強制撰寫 right labeled

**Comment by gnehs** [comment]
建議你在說明文件特別附註一下，不然真的不知道怎麼用 Orz

**Comment by YamiOdymel** [comment]
這個用法原本是我過度設計出來的產物，沒考慮到有人真的會用…。

**Comment by YamiOdymel** [comment]
我之後會把他加在範例裡面，如果你有些奇怪的用法可以去看看 test 資料夾裡面，可能會有幫助

**Comment by gnehs** [comment]
好的

2017年3月28日 下午8:41，"Yami Odymel" <notifications@github.com>寫道：

我之後會把他加在範例裡面，如果你有些奇怪的用法可以去看看 test 資料夾裡面，可能會有幫助

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/TeaMeow/TocasUI/issues/225#issuecomment-289757003>, or mute
the thread
