### ISSUE TITLE
menu 應能將選單項目置於.container裡

### ISSUE THREAD

**Issue by itshenrywu** [teacat/tocas#24]
Like this:
http://bootswatch.com/cerulean/

**Comment by YamiOdymel** [comment]
Menu 可以放到 Container 裡，怎麼了嗎

**Comment by itshenrywu** [comment]
但那一整條(背景顏色)會被侷限在container裡
而我希望的是那一條背景顏色是滿版(fluid)，但裡面的項目能在container中

（好難解釋
