### ISSUE TITLE
新增對話方塊

### ISSUE THREAD

**Issue by itshenrywu** [teacat/tocas#25]
像是BS的model，可以圖片或文字，
或是像Sweetalert那樣，取代傳統的window.alert。

**Comment by YamiOdymel** [comment]
現在其實很少地方在用 Alert 了 ..

對我來說我會認為需要 Alert 的地方可能算是設計不當，

你可以稍微敘述一下哪裡需要這種視窗嗎？

**Comment by YamiOdymel** [comment]
這裡有一些關於「為什麼你不應該繼續使用對話視窗」的相關討論。

http://stackoverflow.com/questions/361481/when-are-modal-dialogs-truly-necessary

http://stackoverflow.com/questions/361493/why-are-modal-dialog-boxes-evil

-- 編輯

http://stackoverflow.com/questions/152938/when-is-modal-ui-acceptable

**Comment by itshenrywu** [comment]
有道理，不過我需要做圖片燈箱
對話可能就不需要了。

**Comment by YamiOdymel** [comment]
圖片燈箱的話會很建議你自己動手做，

畢竟光是關閉按鈕該放哪裡，

之類的那種樣式就有很多不同的解答了。

**Comment by itshenrywu** [comment]
Ok.

**Comment by YamiOdymel** [comment]
Reopen this issue for #129, though I not sure if I should add Modal or not 🌚

**Comment by YamiOdymel** [comment]
HTML5 的 `<dialog>` 也許會派上用場。

**Comment by YamiOdymel** [comment]
基本的 Modal 雛型已經做好了，並且支援捲軸滾動與大小（`mini`, `tiny`, `small`, `(自動伸縮)`, `large`）。接下來需要等待 JavaScript 實作。

![screen shot 2017-01-12 at 6 33 47 am](https://cloud.githubusercontent.com/assets/7308718/21869195/54a25412-d891-11e6-89c2-75fd74ac11a0.png)
![screen shot 2017-01-12 at 6 32 12 am](https://cloud.githubusercontent.com/assets/7308718/21869196/570e2adc-d891-11e6-82cb-8b816171cc10.png)
![screen shot 2017-01-12 at 6 34 59 am](https://cloud.githubusercontent.com/assets/7308718/21869185/4f1db8a6-d891-11e6-9a21-574ca8cc72a0.png)
![screen shot 2017-01-12 at 6 34 31 am](https://cloud.githubusercontent.com/assets/7308718/21869191/518b62c8-d891-11e6-9b54-28ef975a89ac.png)

**Comment by YamiOdymel** [comment]
已新增與 Commit，尚未 Release。
