### ISSUE TITLE
希望可以增加右鍵開啟選單功能

### ISSUE THREAD

**Issue by yeungalan** [teacat/tocas#267]
![image](https://cloud.githubusercontent.com/assets/12872405/25314047/939e6e30-286e-11e7-8955-8bab35c6c736.png)

類似滑鼠按下右鍵可以彈出選單的功能

**Comment by YamiOdymel** [comment]
我原本是有考慮過這個功能，但是想起來不太實際所以就暫時住手了。

主要的原因有這幾個：

1. 使用者通常會假設右鍵選單是原生選單，而非網站自訂功能的右鍵選單。（所以自訂右鍵選單很難被發現。）
2. 行動裝置上的右鍵選單會被閹割，沒有辦法呈現。

_（額外閱讀：[原文] [網頁應用程式的右鍵選單：好、還是壞主意？](http://stackoverflow.com/questions/779689/right-mouse-click-in-web-applications-good-or-bad-idea)）_

不過仔細想起來 Google Docs 確實有自訂右鍵功能，他們的網頁做的很像一個應用程式，不會讓你有網頁的感覺，這種時候用上右鍵選單貌似就沒什麼衝突（雖然我覺得 Tocas UI 很難做的像原生應用程式般）。

如果你的用途是像你編輯前的那張圖（有點像編輯名稱什麼之類的功能），我通常會建議直接在頁面上擺放編輯按鈕讓使用者進入使用模式，減少浮動的元素（不然感覺元素好容易溢出螢幕）。

雖然話是這麼說，這個功能還是在考慮範圍就是了，不過可能還要再想一下，剛才要實作的時候發現要寫一堆 CSS 覆蓋有點小麻煩。

![6fe3b1579c6bda2f1d218243a0db8128_w48_h48](https://cloud.githubusercontent.com/assets/7308718/25314365/1d85d196-2875-11e7-8d7f-6c605afc6083.gif)

**Comment by YamiOdymel** [comment]
稍微實作了一下

![ezgif-1-ec6f34ae55](https://cloud.githubusercontent.com/assets/7308718/25314737/26107db4-287c-11e7-9f5d-3a668bea4a11.gif)

**Comment by gnehs** [comment]
![1493989357 0505 2102](https://cloud.githubusercontent.com/assets/16719720/25746474/43e48926-31d6-11e7-8ae8-6367f05aea04.png)
HTML5 有支援這個功能，然後只有 Firefox 能用
https://www.w3schools.com/tags/tag_menuitem.asp
![1493989430 0505 2103](https://cloud.githubusercontent.com/assets/16719720/25746519/7967e700-31d6-11e7-8f8b-afa03b7e1982.png)

**Comment by yeungalan** [comment]
只支援Firefox那這東西有什麼作用wwwww

**Comment by YamiOdymel** [comment]
我也覺得那個東西只支援 Firefox 有夠夭壽可惜的，順帶一提這個功能已經解決了（12 天前），會在 Tocas UI 2.3 釋出，不過這次的更新有很多很多東西⋯⋯所以我正在趕。
