### ISSUE TITLE
吸附標籤可放於表格欄位?

### ISSUE THREAD

**Issue by itshenrywu** [teacat/tocas#33]
在做月曆時可以用來顯示日期。

**Comment by YamiOdymel** [comment]
哪一種吸附標籤？

**Comment by itshenrywu** [comment]
![screenshot_2016-05-11-17-34-24](https://cloud.githubusercontent.com/assets/8154476/15176666/caa2801e-1731-11e6-990c-c7d46b0c18e5.png)
