### ISSUE TITLE
[T2] 給 <kbd> <code> 等預設樣式

### ISSUE THREAD

**Issue by YamiOdymel** [teacat/tocas#379]
https://v4-alpha.getbootstrap.com/content/code/

![2017-06-01 7 18 56](https://cloud.githubusercontent.com/assets/7308718/26658120/a5f30c86-469a-11e7-9c38-ac0658b5f739.png)

**Comment by gnehs** [comment]
你還說不會弄的🌚🌚🌚

**Comment by YamiOdymel** [comment]
@gnehs 這些東西大概增加了不少的大小，如果你覺得沒必要的話我就不用新增了。

**Comment by gnehs** [comment]
新增啦，寫 Blog 很好用

**Comment by YamiOdymel** [comment]
@gnehs 建議你把 Blog 會用到的標籤列出來，這樣我比較好做參考

**Comment by gnehs** [comment]
@YamiOdymel 
`<h1>~<h6>` `<kbd>` `<code>` `<blockquote>` `<p>` `<a>` `<input>` `<button>` `<hr>`
我會用到的差不多就這樣惹
