### ISSUE TITLE
使用側邊欄時會出現捲軸，明明高度夠的說 QQ

### ISSUE THREAD

**Issue by gnehs** [teacat/tocas#389]
![1496756126 0606 2135](https://cloud.githubusercontent.com/assets/16719720/26831923/5c783b2a-4b00-11e7-9558-546f44f8c598.png)
![1496756225 0606 2137](https://cloud.githubusercontent.com/assets/16719720/26831962/851a9ff0-4b00-11e7-904e-481cf9cbe167.png)

**Comment by gnehs** [comment]
改成 auto 啦

**Comment by YamiOdymel** [comment]
上個修正才把 Sidebar 改成 Auto，結果沒想到 Pusher 也要www
