### ISSUE TITLE
對 .ts.icon.labeled.button 內的 icon 指定大小會沒有效果

### ISSUE THREAD

**Issue by coin3x** [teacat/tocas#391]
As title

```
<a class="ts icon labeled button"><i class="mail icon large"></i>Email</a>
```
![image](https://cloud.githubusercontent.com/assets/9127594/26833082/f677e09c-4b03-11e7-8d4f-70f7decd8def.png)

**Comment by lekoOwO** [comment]
偷我的issue 討厭鬼(#

**Comment by YamiOdymel** [comment]
<img width="193" alt="2016-06-08 7 20 07" src="https://cloud.githubusercontent.com/assets/7308718/26834828/0be547e4-4b09-11e7-8eb2-71babc9c7728.png">

**Comment by YamiOdymel** [comment]
照修正之後會長成這樣

![2017-06-07 12 29 07](https://user-images.githubusercontent.com/7308718/26840321-579a6e30-4b18-11e7-9297-f1ecf65d1b2a.png)

怎麼感覺有點大

---

幹你別只會笑給點辦法 

↓

**Comment by lekoOwO** [comment]
我覺得變大之後跟basic button很搭
