### ISSUE TITLE
Wordpress上Jetpack提供的分享按鈕的樣式被吃掉了

### ISSUE THREAD

**Issue by lekoOwO** [teacat/tocas#397]
![image](https://user-images.githubusercontent.com/20151124/26880651-abb630a8-4bc7-11e7-8873-9fda8c43e7b1.png) 

正常應該顯示在同一行而且沒有開頭的點點
參考https://blog.rextw.ga/published/
分享按鈕功能我就先不關了。

**Comment by YamiOdymel** [comment]
如果可以的話你需要將那個 `<ul>` 加上 `.unstyled` 的樣式阻止被套用 Tocas 外觀，

不行的話⋯⋯這裡有暫時的解法，因為目前我還不打算取消掉這個功能⋯⋯

**JavaScript**

```js
$.ready(() => { $('.sd-content > ul').addClass('unstyled'); });
```

這能在網頁載入完之後替該 `<ul>` 套用 `unstyled` 來避免被套用 Tocas 樣式。

**Comment by lekoOwO** [comment]
用這個似乎不起效果

```javascript
$.ready(() => { $('.sd-content > ul').addClass('unstyled'); });
```
但使用這個成功了。
```javascript
$('.sd-content > ul').addClass('unstyled');
```

**Comment by gnehs** [comment]
下面那個是 JQ
