### ISSUE TITLE
側邊欄增加其他顯示形式

### ISSUE THREAD

**Issue by itshenrywu** [teacat/tocas#398]
除了原本的 Push，希望能新增 Overlay 或其他形式
https://semantic-ui.com/modules/sidebar.html#/examples

**Comment by YamiOdymel** [comment]
目前有 Overlay 的樣式：[https://tocas-ui.com/modules/sidebar/#覆蓋的](
https://tocas-ui.com/modules/sidebar/#覆蓋的)

其他方式看起來蠻酷炫但是卡卡的，會考慮新增
