### ISSUE TITLE
Slate with image icon bug

### ISSUE THREAD

**Issue by toby3d** [teacat/tocas#399]
# Issue Report
## What I did...
```html
<div class="ts clickable slate">
    <i class="image faded icon"></i>
    <span class="header">Add post cover</span>
    <span class="description">點擊此處會有相關的回饋效果。</span>
</div>
```
## What I expected...
Result with image icon like this:
![image](https://user-images.githubusercontent.com/5412322/26901840-92ee62e2-4bf0-11e7-9563-abb780b6b174.png)

## What I get...
![image](https://user-images.githubusercontent.com/5412322/26901783-7263e2cc-4bf0-11e7-9501-4f93559f6983.png)

**Comment by toby3d** [comment]
Same bug by use `file image outline` icon. So - `image` class break some styles in slate.

**Comment by YamiOdymel** [comment]
This also fixed for `.video.icon`
