### ISSUE TITLE
對話框在原始碼檢視的情況下，陰影怪怪的

### ISSUE THREAD

**Issue by gnehs** [teacat/tocas#409]
不知道是否只發生在手機，瀏覽器是 Chrome 最新版
Tocas UI Bug https://imgur.com/gallery/WR3Uc

![2017-06-10 6 45 59](https://user-images.githubusercontent.com/7308718/27002185-10a21c56-4e0d-11e7-8b43-13552dcad474.png)

**Comment by YamiOdymel** [comment]
![screenshot_2017-06-10-19-18-47](https://user-images.githubusercontent.com/7308718/27002331-c1c82444-4da4-11e7-9a80-78c79cbb9e28.png)

慘了，我沒這問題

**Comment by gnehs** [comment]
等等我開除錯工具看看

**Comment by gnehs** [comment]
我用金色版的沒問題，看來是 Chrome 導致的
