### ISSUE TITLE
範例關閉失效

### ISSUE THREAD

**Issue by itshenrywu** [teacat/tocas#414]
RT
https://tocas-ui.com/collections/message/javascript

**Comment by gnehs** [comment]
因為他只是展示關閉按鈕而已

**Comment by YamiOdymel** [comment]
主要是因為 Tocas 已經採用了新的 `.ts.close.button` 而非原本的 `i.close.icon`，

導致 `.message()` 無法將關閉按鈕的功能綁定在 `i.close.icon` 上，延後到 2.4 與新模塊一同修復。

**Comment by YamiOdymel** [comment]
將修正於新文件。
