### ISSUE TITLE
 https://tocas-ui.com/try/ 問題回報

### ISSUE THREAD

**Issue by yeungalan** [teacat/tocas#418]
# Issue Report
在測試sidebar的效果時整個網站爆了ww
![image](https://user-images.githubusercontent.com/12872405/27024484-52d0ed96-4f89-11e7-96f3-19f308d87a44.png)

//所貼上的的元件html code
    
    <div class="ts left sidebar">
    </div>
    

    
    <div class="pusher">
        
    </div>
    
//完

預計應該會有頁面推動器出現w

最終結果就是整個網都不能動和不能輸入，須要F5後才可回復正常

**Comment by YamiOdymel** [comment]
> 按下「F」按鍵進行哀悼。

因為遊樂場頁面實際上是更改 Div 的 HTML，而不是建立一個 `<iframe>` 來擺放新的 HTML 內容，

而 `.pusher` 是一個會遮蔽頁面帶有白色背景的元素，所以就炸掉了。還有人直接在遊樂場裡打上 `<link>` 引用外部樣式，或是打個 `<html>` 就又炸掉了。

修復不了，謝謝遊樂場帶給我們的歡樂，記憶將永留存於我們心中。

_RIP 遊樂場——2017_
