### ISSUE TITLE
範例好像跑版了

### ISSUE THREAD

**Issue by gnehs** [teacat/tocas#419]
![1497338798 0613 1526](https://user-images.githubusercontent.com/16719720/27070813-181b7a26-504d-11e7-90ac-81342e9ba5a0.png)
![1497338828 0613 1527](https://user-images.githubusercontent.com/16719720/27070814-19194d40-504d-11e7-9055-30fc65a6a41a.png)

https://tocas-ui.com/collections/form/#欄位錯誤

**Comment by YamiOdymel** [comment]
主要是 Form 裡面的 Label 會對 Checkbox 的 Label 做出奇異舉動，相同於 #407
