### ISSUE TITLE
輸入欄位可以組合

### ISSUE THREAD

**Issue by itshenrywu** [teacat/tocas#420]
希望輸入欄位能跟標籤、按鈕或其他輸入欄位組合。

![default](https://user-images.githubusercontent.com/8154476/27134244-920f8b2e-5147-11e7-9b5e-7238ebeee71d.png)

**Comment by YamiOdymel** [comment]
確實可以，看來是文件忘記加上這個功能了。  [`遊樂場連結`](https://tocas-ui.com/try?html=%3Cdiv%20class=%22ts%20labeled%20action%20input%22%3E%5Cn%20%20%20%20%3Cdiv%20class=%22ts%20basic%20label%22%3E@%3C/div%3E%5Cn%20%20%20%20%3Cinput%20type=%22text%22%3E%5Cn%20%20%20%20%3Cbutton%20class=%22ts%20button%22%3E%E9%80%81%E5%87%BA%3C/button%3E%5Cn%3C/div%3E)。

![2017-06-14 10 32 37](https://user-images.githubusercontent.com/7308718/27137792-64c26a06-5151-11e7-865e-96092ccc7786.png)

```html
<div class="ts labeled action input">
    <div class="ts basic label">@</div>
    <input type="text">
    <button class="ts button">送出</button>
</div>
```

**Comment by itshenrywu** [comment]
下版文件加入?
