### ISSUE TITLE
語意化的 large 會和響應式的 large device only 產生衝突

### ISSUE THREAD

**Issue by gnehs** [teacat/tocas#425]
板岩會被強制套用 large
```
原始碼(Jade)
.ts.slate 這是原本的
br
.ts.slate.large.device.only large device only
```
![1497927311 0620 1055](https://user-images.githubusercontent.com/16719720/27314595-7a180424-55a7-11e7-87b8-9e722726be9c.png)

**Comment by gnehs** [comment]
![1497927487 0620 1058](https://user-images.githubusercontent.com/16719720/27314629-ab1a393e-55a7-11e7-98e8-fad201a9cc5d.png)
我在弄配種實驗室的時候發現的wwww

**Comment by YamiOdymel** [comment]
這個問題目前還沒有辦法解決，唯一能做的就是把 RWD 的那個額外區分成一個 DIV
```jade
.large.device.only
    .ts.large.slate
```

**Comment by gnehs** [comment]
幫 large device only 改名嗎 🤔🤔🤔

**Comment by YamiOdymel** [comment]
也許 `large device` 可以改成別的，但是想不太到什麼名詞，或者鳥一點可以改成 `data-rwd="large device only"`

**Comment by lekoOwO** [comment]
wide-screen device(#

**Comment by gnehs** [comment]
不能有“-”

**Comment by YamiOdymel** [comment]
而且不一定所有螢幕都是 wide 的

**Comment by gnehs** [comment]
larger device only(###

**Comment by lekoOwO** [comment]
然後lagest device only就誕生了(##

**Comment by gnehs** [comment]
你是要放在時代廣場逆❨X

**Comment by lekoOwO** [comment]
跨年晚會可以用那種(X

**Comment by gnehs** [comment]
那個不夠大
