### ISSUE TITLE
儀表板範例走位

### ISSUE THREAD

**Issue by yeungalan** [teacat/tocas#433]
# Issue Report

錯誤回報時請記得附上 HTML 結構程式碼，還有分成三個章節：
Remember to post the HTML structure and the reproducing steps:

1. 我做了什麼⋯⋯
![image](https://user-images.githubusercontent.com/12872405/27465421-e56b351a-5805-11e7-92d7-8a8f30ae9b08.png)
在小型書面上顯示有問題

2. 我期望什麼⋯⋯
ts card 文字 會在框内

3. 最終結果是⋯⋯
   What I get...
儀表板的ts card 文字被吃掉了

**Comment by YamiOdymel** [comment]
因為沒什麼時間做，所以 Tocas 現在的範例都沒有支援響應式設計（原生範例除外）

因此卡片內容會超出框內也是蠻正常的一件事情，如果是自己在做類似網頁的話在 `.ts.cards` 加上 `.stackable` 就能解決了。

---

2018/01/20 更新：這個問題不打算修正，畢竟範例能越簡潔令人理解越好⋯⋯基本上用個 Stackable 就可以解決了。
