### ISSUE TITLE
Dropdown無法正常使用

### ISSUE THREAD

**Issue by sakkyoi** [teacat/tocas#434]
我使用官網的範例Dropdown的語法，但是自己使用卻無法正常運作，點不開。
有沒有人跟我一樣有這個問題的？

**Comment by YamiOdymel** [comment]
有試著套用且引用 JavaScript 了嗎？如果沒有執行 JavaScript，下拉式選單不會正常運作。

https://tocas-ui.com/modules/dropdown/javascript/

![2017-06-24 10 47 33](https://user-images.githubusercontent.com/7308718/27505122-985a704a-58ca-11e7-8d8a-85b85e91d96c.png)

**Comment by sakkyoi** [comment]
我再試試，謝謝

**Comment by sakkyoi** [comment]
![image](https://user-images.githubusercontent.com/22865542/27506042-9a264ea4-58e2-11e7-9f64-4324bcebbf87.png)
我試著這樣弄，但是還是沒有用

**Comment by sakkyoi** [comment]
原來是要放在後面，解決了。謝謝

**Comment by gnehs** [comment]
Tocas UI 都這樣的 QQ

**Comment by YamiOdymel** [comment]
@gnehs 這是正常的 JavaScript 讀取先後順序的問題，JavaScript 就在頁面讀取完之前會被執行，所以會找不到頁面上的元件。

用 jQuery 的時候也會有這樣的問題發生，如果要防止這個問題，通常是將 script 放到 body 內部的最後面，或者使用 `$.ready()` 函式來在頁面讀取完畢後才執行 JavaScript。
