### ISSUE TITLE
.modal .content 內的按鈕按了會直接讓 Modal 隱藏

### ISSUE THREAD

**Issue by itshenrywu** [teacat/tocas#444]
RT

有辦法讓他不會按了就隱藏嗎？

**Comment by YamiOdymel** [comment]
你的按鈕有包含 `.positive, .approve, .ok, .negative, .deny, .cancel` 其中一個樣式嗎？

如果有，試著更改選項解決這個問題。如果沒有，就是 Bug 欠修

![2017-07-04 12 09 08](https://user-images.githubusercontent.com/7308718/27814787-9e164844-60b1-11e7-9908-25d47067694a.png)

**Comment by itshenrywu** [comment]
沒欸 只有 .inverted
