### ISSUE TITLE
[功能建議]時間軸功能

### ISSUE THREAD

**Issue by gnehs** [teacat/tocas#451]
![-1](https://user-images.githubusercontent.com/16719720/28402721-d3e3a602-6d53-11e7-9fbe-17938dac590a.png)
大概長這樣，然後希望可以讓 Tocas.js 來調整寬度來符合時間的距離(這個希望可以給用戶自己調整是否開啟)

**Comment by lekoOwO** [comment]
![image](https://user-images.githubusercontent.com/20151124/28402997-47d3ed96-6d55-11e7-8f56-47debc61d333.png)
這種的也順便，謝謝(#

**Comment by gnehs** [comment]
![image 003](https://user-images.githubusercontent.com/16719720/28403039-74e9024e-6d55-11e7-8951-5866d2650ea8.png)
再畫一張
時間不重要，亂寫的

**Comment by lekoOwO** [comment]
http://blog.infographics.tw/2016/04/use-labella-for-timeline/

好像不用從 0 幹起的樣子

**Comment by gnehs** [comment]
剛剛想了一下 CSS 可以怎麼寫之後，感覺洨洨安會弄到爆肝

**Comment by lekoOwO** [comment]
這是重要的 improvement (X

**Comment by YamiOdymel** [comment]
基本上會由 Feed 去做改良，新增一個 `.ts.timelined.feed` 樣式。

至於水平時間軸就沒什麼辦法了（除非你想每打一個字就 `<br>` 一次）

![2017-08-03 7 17 38](https://user-images.githubusercontent.com/7308718/28919563-9e0f17f4-7880-11e7-8ab7-a20b6a923f52.png)

**Comment by gnehs** [comment]
能夠根據時間來調整外距嗎🤔

**Comment by lekoOwO** [comment]
根據時間來調整外距的話就沒辦法做第二層了吧 OAO

**Comment by YamiOdymel** [comment]
也許你可以考慮透過時間來增加 `<br>` 達到調整外距的效果 🤔

**Comment by gnehs** [comment]
好ㄅ

**Comment by YamiOdymel** [comment]
我是還想不太到怎麼透過 JavaScript 調整長度啦⋯⋯ 🤔

**Comment by YamiOdymel** [comment]
@gnehs 你有想到 JavaScript 的部分應該怎麼呼叫、使用嗎？

**Comment by gnehs** [comment]
弄個 json 格式，然後拿 js 去算時間，之後產生對應的時間軸和 `<br>` (?

**Comment by gnehs** [comment]
```js
timelined=[
    {
        title:"歡慶始春1周年",
        time:"2017/08/12 08:09",
        summary:"owowo",
    },
    {
        title:"歡慶始春2周年",
        time:"2018/08/12 08:09",
        summary:"owowo",
    },
    {
        title:"歡慶始春3周年",
        time:"2019/08/12 08:09",
        summary:"owowo",
    },
]
```

**Comment by YamiOdymel** [comment]
@gnehs 照這種用法，要怎麼知道要產生多少「`<br>`」？

總不可能每一個小時就一個 `<br>`，那麼敘述年份的網頁不就夭壽長 🤔

**Comment by gnehs** [comment]
計算他們的比值，化簡

**Comment by gnehs** [comment]
感覺累死
#嘴砲寫code

**Comment by gnehs** [comment]
https://picturepan2.github.io/spectre/experimentals/timelines.html
