### ISSUE TITLE
下拉式選單收起後的下方區塊點擊閃爍

### ISSUE THREAD

**Issue by SnailPJW** [teacat/tocas#453]
# Issue Report

1. 我做了什麼⋯⋯
   What I did...
  
- 我使用了下拉式選單 (https://tocas-ui.com/modules/dropdown/#項目) , 點擊旁邊空白處可以收回menu,但是滑鼠游標移動到 下拉式選單 下面區塊時, 游標會呈現可以點擊的狀態!? 點擊後會閃爍下拉式選單的menu

感謝您!!!

**Comment by YamiOdymel** [comment]
使用的是什麼瀏覽器？我在 Chrome 上沒有辦法重現這個問題？

**Comment by SnailPJW** [comment]
果然如您所說的! Chrome 不會有這樣的問題!  我使用的是 Firefox ! XD 感謝您!
