### ISSUE TITLE
tooltip 在 speech 會死掉

### ISSUE THREAD

**Issue by itshenrywu** [teacat/tocas#454]
![default](https://user-images.githubusercontent.com/8154476/28528336-02079470-70c0-11e7-8b10-d655e22c6947.png)
RT

**Comment by YamiOdymel** [comment]
這個問題基本上只有修一半，沒辦法完全解決（因為 Div 的容器會等寬、和 Flexbox 的奇異觀念）。也許 Tocas 2.4 的 Popup JavaScript 模塊可以解決。

當 `content` 元素後面有 `meta` 時，會一樣失效。需要在 `content` 之外用一層 `div` 包裹著，並且將 `data-tooltip` 轉移到這個 `div` 上。

```html
<div class="ts speeches">
    <!-- X: 不要這樣 -->
    <div data-tooltip="我是文字" class="speech">
        <div class="content">
            <div class="text">
                Speech Tooltip
            </div>
        </div>
    </div>

    <!-- X: 不要這樣 -->
    <div class="speech">
        <div data-tooltip="我是文字" class="content">
            <div class="text">
                Content Tooltip
            </div>
        </div>
    </div>

    <!-- O: 請這樣做 -->
    <div class="speech">
        <div data-tooltip="我是文字">
            <div class="content">
                <div class="text">
                    Content Wrapper Tooltip
                </div>
            </div>
        </div>
    </div>
</div>
```

不過要是不使用 JavaScript 解決的話，搭配 `meta` 仍會遇上下列問題就是了⋯⋯。

**Meta 移位**

![2018-01-18 11 59 03](https://user-images.githubusercontent.com/7308718/35080231-38b83a5c-fc47-11e7-844d-0ad5d86033be.png)

---

**Tooltip 移位**

![2018-01-18 11 59 38](https://user-images.githubusercontent.com/7308718/35080232-38ea7058-fc47-11e7-89aa-2b00cc35a4b4.png)
