### ISSUE TITLE
[錯誤] icon 在開啟 .ts.modal 後未受shadow影響

### ISSUE THREAD

**Issue by yeungalan** [teacat/tocas#461]
![image](https://user-images.githubusercontent.com/12872405/28744465-122ffe78-7494-11e7-95a2-864638d65744.png)

在 https://tocas-ui.com/modules/modal/javascript 中就可以重現

**Comment by yeungalan** [comment]
![image](https://user-images.githubusercontent.com/12872405/28744547-fe9c4022-7495-11e7-8b75-3d28f84bb528.png)
看上來還有optionModal 啟動時的 shadow 不會覆蓋到整個頁面

**Comment by YamiOdymel** [comment]
後面這個問題有發現是因為 Dimmer 放在 `.pusher` 裡面所發生的問題。

https://github.com/TeaMeow/TocasUI/issues/430
