### ISSUE TITLE
動態的時間在事件或使用者名稱的下方

### ISSUE THREAD

**Issue by goodjack** [teacat/tocas#465]
參考以下來源：

- Facebook 動態
![image](https://user-images.githubusercontent.com/1116129/28750886-1aced5bc-752b-11e7-9353-d2d743d5d0e3.png)

- Facebook 通知
![image](https://user-images.githubusercontent.com/1116129/28750884-106167ac-752b-11e7-8d3b-c4cbef9a8978.png)

- Product Hunt Ask
![image](https://user-images.githubusercontent.com/1116129/28750889-4b9cb8d0-752b-11e7-80bb-8dafe865e417.png)

謝謝~

**Comment by YamiOdymel** [comment]
這個功能研究了幾個月了，基本上因為 CSS Selector 太殘廢而沒辦法生出來。

問題在於當 Date 擺置於名稱後，會有不對齊的問題。而 Selector 又沒辦法寫得像 If 條件式那樣。

> 如果 xxx 後面有 yyy，那麼就 zzz。

---

事實上，我很想新增一個專門擺放使用者頭像、中繼資料、暱稱那樣的元素（簡單說就是 Facebook 那樣），但又想不到什麼名稱（例：`.ts.person`、`.ts.profile`）。

如果真的生出來了，又會跟 Feed、List 那些樣式重複反倒增加使用者選擇元件時的困惑⋯⋯還在思考這個問題。

暫時的解決方法是在 Tocas 3.0 採用 .ts.list 來擺置這類的內容。

**Comment by goodjack** [comment]
目前我嘗試比較接近的做法是把 .date 放到 .meta 裡面
但這用法應該不是原始設計吧

![image](https://user-images.githubusercontent.com/1116129/35557014-d7c556d4-05de-11e8-95a9-5f1a4d49bb4d.png)


遊樂場：https://goo.gl/mYU5tk
``` html
<div class="ts feed">
    <div class="event">
        <div class="label">
            <i class="inverted info circular comment icon"></i>
        </div>
        <div class="content">
            <div class="summary">
                <a>Yami Odymel</a> 和你成為了朋友。
            </div>
            <div class="meta">
                <div class="date">
                    1 小時前
                </div>
            </div>
        </div>
    </div>
</div>
```

**Comment by YamiOdymel** [comment]
通常會放在 `.summary` 後面，但這樣就會偏移了。

![2018-01-30 5 48 32](https://user-images.githubusercontent.com/7308718/35559504-da058c0a-05e5-11e8-9f2c-a6a828d7bf71.png)
