### ISSUE TITLE
请考虑增加电商元素或样式

### ISSUE THREAD

**Issue by jet10000** [teacat/tocas#471]
比如，订单，商品列表，购物车等。

**Comment by YamiOdymel** [comment]
有實際範例可供參考嗎？因為 Tocas 元件和其他樣式框架不一樣的地方在於，你可以拼湊 Tocas 元件而達成自己要的，所以不是每種東西都有（例如「付費方案」可以用「卡片」元件拼湊而成）。

Tocas UI 官方網站有現成的範例可供參考。
https://tocas-ui.com/examples

---

像你說的訂單（發票）這裡有實際範例：
https://examples.tocas-ui.com/pages/invoice.html
![2017-07-31 4 51 51](https://user-images.githubusercontent.com/7308718/28770122-94378652-7610-11e7-85d9-d312b97256ee.png)

---

而購物車⋯⋯這也許算其中一種：
https://examples.tocas-ui.com/pages/payment.html
![2017-07-31 4 52 04](https://user-images.githubusercontent.com/7308718/28770129-9b90b590-7610-11e7-9f49-d0233d7e4b6b.png)

**Comment by YamiOdymel** [comment]
想不太到少了什麼，暫時先關閉，如果想到了奇異的新東西就開新的 Issue 或重啟 Issue 吧。
