### ISSUE TITLE
开发TocasUI的环境，工具，流程都包括哪些？

### ISSUE THREAD

**Issue by jet10000** [teacat/tocas#481]
开发TocasUI的环境，工具，流程都包括哪些？

想调试一些东西，没找到相关开发者文档。文档基本上是从使用者角度出发写的。

**Comment by YamiOdymel** [comment]
Tocas UI 基本上只有用到 Sass（先撇開 JavaScript 的部分不說，那部分 2.4 會有重大異動），

簡單說你只要安裝 Sass（這個是 Ruby Sass，效能極慢，但安裝最為簡單。你可以考慮 Node Sass 或 SassC⋯⋯只要是 Sass 都可以）：

```bash
npm install sass
```

然後透過 Sass 指令，監聽 `src/tocas.sass` 的任何修改動作，自動編譯到 `dist/tocas.css` 即可。

```bash
sass --watch src/tocas.sass:dist/tocas.css --style compressed
```

接下來就能修改 `src/` 裡的所有文件，會自動編譯到 `dist/` 中，至於測試的部分我是自己用肉眼測試的，請參考 `/tests` 資料夾（這種測試應該會累死人）。
