### ISSUE TITLE
新增快速搜尋字典功能

### ISSUE THREAD

**Issue by jet10000** [teacat/tocas#482]
Semantic-UI的语义方式非常好，但个人觉得对使用者也带来一个问题：记忆更多细节。因为现在开发很多时候用到智能的IDE，都有智能提示，比如Webstrom，这样当我输入container后，能提示container__narrow，container__very__narrow等等。这种BEM的命名法，不用去记忆太多细节和修饰，也有所属域，个人感觉挺方便的，不知道有没有可能在编译sass文件时有转成BEM命名方式css的功能。

http://getbem.com/naming/

纯属个人偏好，仅提供交流参考。

**Comment by YamiOdymel** [comment]
我猜應該沒有辦法做這樣的轉換（至少我還沒看見過）。

我有參考過 BEM 的命名方式，但因為看見 Bootstrap 那樣的 `m-l-1`、`p-x-1` 之類的邪門用法，還有[像這樣](https://getmdl.io/components/index.html#buttons-section)：

```html
<button class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored">
  <i class="material-icons">add</i>
</button>
```

夭壽長的類別名稱，我就不怎麼打算採用 BEM 了。

不過像你說的，自動完成的優勢還蠻吸引人的，和團隊進行合作時我猜優勢也會比較大些（不需要翻閱文件，層次分明）。但如果你打算使用 Tocas UI 的話，我想你只能好好記住英文了。

---

參考連結：

[Semantic UI - BEM Flow](https://github.com/Semantic-Org/Semantic-UI/issues/3671)
[Semantic UI - Word Order Dependency](https://github.com/Semantic-Org/Semantic-UI/issues/396)
[Semantic UI - Name !!! difficult](https://github.com/Semantic-Org/Semantic-UI/issues/3344)
[css-chassis - Naming convention](https://github.com/jquery/css-chassis/issues/4)

**Comment by jet10000** [comment]
可以做一个单页的快速查找的索引列表，方便查询。

**Comment by YamiOdymel** [comment]
這個主意是不錯
