### ISSUE TITLE
類似 Spotify 分類的效果？

### ISSUE THREAD

**Issue by goodjack** [teacat/tocas#483]
截圖範例：
![image](https://user-images.githubusercontent.com/1116129/29083319-f3533cb2-7c2d-11e7-8923-de39c5be234c.png)

不知道該怎麼稱呼這個效果
- 圖片當按鈕背景
- 圖示在圖片上面
- 還是圖片當按鈕背景，而且圖示在背景上面？

謝謝~

**Comment by YamiOdymel** [comment]
這個功能有點類似 #457，考慮到會在上面顯示各式各樣的元件，

結構可能會偏向：

```html
<div class="ts image">
    <div class="overlay">
        <i class="heart icon"></i>
    </div>
    <img src="my-img.png">
</div>
```
