### ISSUE TITLE
Mozilla Focus + Tocas UI

### ISSUE THREAD

**Issue by jet10000** [teacat/tocas#493]
最近看到Mozilla的focus-ios/android项目，虽然是个匿名浏览器，但我在查看该项目时候产生了结合Tocas-ui的想法。如果能结合起来，就能形成了一个完整的Web移动端解决方案。浏览器依然是浏览器，网页依然是网页，这样就可以直接把网站打包成应用进行安装。虽然像crodova也能做到，但如果让focus和tocas结合，风格上浑然一体，就提供了整套移动端前端定制解决方案，而不仅仅是UI。这是一种简易实用低成本的绿色环保方案。

**Comment by YamiOdymel** [comment]
稍微看了一下，Focus 是個瀏覽器，不曉得你的提議是不是跟我目前的想法：「讓 Tocas UI 能夠做出像 Native Apps」相似。

我目前是有正在讓 Tocas UI 的介面、元件更趨向於能夠做出類似原生應用程式的方向前進。例如說新增 [Bottom Sheet](https://github.com/TeaMeow/TocasUI/issues/357)、[Toolbar](https://github.com/TeaMeow/TocasUI/issues/491)、[支援滑動](https://github.com/TeaMeow/TocasUI/issues/478)⋯等。

畢竟在使用 [Semantic UI](https://semantic-ui.com)、[Bootstrap](https://v4.bootcss.com/) 的時候，我意識到他們的 UI 不太適合開發類似原生應用程式的東西⋯⋯。

**Comment by jet10000** [comment]
对，到又有一些差别，我目前接触的一些项目，比如react native的nativebase，ionicframework ，vuejs等，它们都在试图更像本地应用并跨平台，就是说它们都在试图用web技术做应用。但focus+tocas，既提供一个可定制打包的浏览器，同时又打开是真正的web。这样充分利用Web后端框架一些优势，同时又有一个可定制的浏览器的优势，作为前端方案想象空间就更大了。你可以把focus浏览器在手里上安装试试。

**Comment by jet10000** [comment]
如果让Tocas-UI像Native Apps，我担心会走向模仿Native Apps的路途，而这个工作其实有很多项目都在做，有半途而废的，有走到较好的，比如ionicframework 。Tocas-Ui要做的我觉要像移动端的Webpage，而不是本地应用的Screen。而有一款结合的可自定义的浏览器就如虎添翼。从一般用户习惯角度讲他们在移动端很少打开浏览器输入网址，多半是一些社交应用里的网址跳转，或者直接打开本地应用。另外，像chrome，safari 有将网站添加到桌面功能，但前提是用户得通过浏览器打开网址后才能做，非常不直接。而通过focus打包的话，用户下载应用安装在心理上已经形成了习惯。

**Comment by jet10000** [comment]
还有就是项目定位问题，像Google的material.io的web，设计不可谓不精良，理念不可谓不先进，但真正在实际项目中又觉得不实用，很难用在实际的项目中。Tocas-UI自己的定位是什么呢，我个人目前觉得企业级项目会选择使用，一些互联网的初创型公司一些项目会使用。

**Comment by jet10000** [comment]
如果要做原生Native Apps的UI，我个人觉得应该新建一个项目Tocas-App-UI，而这个应该叫Tocas-Web-UI

**Comment by zypeh** [comment]
@jet10000 首先我很好奇你会想到 Focus browser 而不是 electron 还是 servo runtime。

至于你说的针对 PWA 的 UI 风格定位我个人认为还是不错的。可能需要深入探讨这点。 :)

**Comment by jet10000** [comment]
electron和servo都不能在iOS上吧，苹果有政策限制。另外，如果打包

**Comment by jet10000** [comment]
如果打包，这些打包出来文件都比较大。先前我看过crosswalk项目，但因为PWA的发现，项目已经不再维护了。

**Comment by jet10000** [comment]
像focus这种浏览器，简易，二次开发的可能性大。

**Comment by jet10000** [comment]
目前的Tocas-UI在做为系统管理后台，传统网站前台，企业级系统，都是非常适合的。

现在前端开发日趋复杂，一旦复杂，使用者学习和或者熟悉成本加大。所以更加轻快的项目更有竞争力。

**Comment by YamiOdymel** [comment]
這主意是很不錯，問題在於要怎麼將網頁轉換成 Native Apps，修改 Focus 的話我可不會 Java（Kotlin 看起來倒是很好玩）。

我是蠻喜歡類似 Ionic Framework 那樣的開發模式，但是為了這樣而打造一個像 Vue.js、React.js 的 Framework 也太大手筆了一點，聽起來根本夭壽難，不過能的話貌似也很有趣。

轉成開發 Vue.js 和 React.js 的 Components 也許還會簡單點（然後用上 Weex 或 React Native 之類的東西？）。

至於要把專案區分成 Web 和 Native 的話⋯⋯則要再看看。因為我希望兩者能夠併在一起使用，這樣就不用額外去讀取 Native 或 Web 的版本，而且不需要學習額外的安裝方式和元件。

雖然如果要開發 Native 方面就會ㄧ同引用到 Web 就是了。

**Comment by jet10000** [comment]
这里有个json转native apps
https://jasonette.com/

**Comment by jet10000** [comment]
https://www.ampproject.org/

基于amp技术，重构一套Tocas-UI，能站在巨人的肩上。再结合Focus，就是轻量级的App

**Comment by jet10000** [comment]
如果基于vuejs，其实像element这些UI已经够用。
http://element.eleme.io/#/zh-CN

**Comment by jet10000** [comment]
Ionicframework 是基于angularjs和cordova的。

对应的话，Tocas能基于amp和focus，就有点意思了。但amp有太多限制。不过可以朝这个方向走。

**Comment by jet10000** [comment]
Weex，react native 都是大工程，还是别走这条路，太累。比如基于RN的 expo.io

**Comment by jet10000** [comment]
http://goratchet.com/components/

像这种，模仿app，没有热度的。

**Comment by YamiOdymel** [comment]
稍微標記一下，這個問題可能和下列有關。

https://github.com/Semantic-Org/Semantic-UI/issues/246
https://github.com/Semantic-Org/Semantic-UI/issues/241

**Comment by YamiOdymel** [comment]
其實這麼看下來，我還是想不透這個的主題是什麼，是讓 Tocas UI 有一套能夠打造 Native Apps 機制嗎？這意味著需要搭配修改過的 Focus + Tocas UI 讓他看起來像 Native Apps？（不過這樣的話仍不能對硬體、檔案進行操作，像 Electron 那樣）

**Comment by jet10000** [comment]
https://preactjs.com/

如果以组件的思维去做Native Apps，其实和reactjs走的路一样。但Tocas可以结合preactjs。这样方便把html转成组件。

**Comment by jet10000** [comment]
很多项目不一定要操作硬件或档案。而且一个项目中不同的方面的需求也是不一样的。比如一个新闻网站：后台新闻内容的管理，就完全可以使用目前的Tocas-UI做成传统的Web，而客户端（iOS，Android）则可以使用Google的AMPproject这样的项目，所以有套UI能基于这些技术完成相应需求，就能得到广泛使用。

Tocas在设计(Design)上可以是统一的，但在实现(Implementation)上可以基于目前各种技术提供UI解决方案。

**Comment by jet10000** [comment]
Focus是UI的宿主，是环境，可以自定义的环境，当然也可以electron, servo runtime，也可以是safari, chrome, IE。不同的项目，不同的需求。

**Comment by coin3x** [comment]
我不懂為什麼做成 native app 會跟 Focus 有關，Focus 使用的瀏覽器引擎還是 Android WebView 啊
