### ISSUE TITLE
輸入框有標籤、自動補完的功能

### ISSUE THREAD

**Issue by goodjack** [teacat/tocas#500]
範例如下：

- Product Hunt
https://www.producthunt.com/posts/new/info

![image](https://user-images.githubusercontent.com/1116129/30249340-34fd184a-9600-11e7-9326-75094f32bbee.png)

- Bootstrap Tags Input ⬅️ 功能能這麼完整就太好了 👏
自動完成好像是搭配 typeahead.js
https://bootstrap-tagsinput.github.io/bootstrap-tagsinput/examples/

![image](https://user-images.githubusercontent.com/1116129/30249419-d6783140-9601-11e7-9fa2-9c1742ca1572.png)

**Comment by YamiOdymel** [comment]
標記一下，可能和 #332 有關
