### ISSUE TITLE
替 2.4 的 Segmented List 加上 Indicated 功能

### ISSUE THREAD

**Issue by YamiOdymel** [teacat/tocas#507]
就像 Table 的 Indicated Column 那樣。

![2017-09-16 11 16 16](https://user-images.githubusercontent.com/7308718/30770385-bb7898b6-a061-11e7-85b2-de6d79d9da7b.png)

**Comment by coin3x** [comment]
![image](https://user-images.githubusercontent.com/9127594/30771058-92508b1e-a071-11e7-9e29-80d22b9877d5.png)
這是你要的效果嗎 🤔

**Comment by YamiOdymel** [comment]
文字的顏色我應該不會改變，改的話好像有點太炫砲了 🤔
大概就是像 Table 那樣只有左邊框顏色改變而已

**Comment by YamiOdymel** [comment]
不過現在的 List 倒是有缺少文字顏色的樣式，貌似又是一個新問題 🤔

**Comment by coin3x** [comment]
自殺
會撞到 positive item

**Comment by YamiOdymel** [comment]
真的，難道說 Indicated 的時候文字顏色不變，沒有 Indicated 的時候變顏色嗎 🤔

**Comment by coin3x** [comment]
好 我先這麼做好了
