### ISSUE TITLE
誰在使用 / Tocas UI Users

### ISSUE THREAD

**Issue by YamiOdymel** [teacat/tocas#516]
基本上這個 Issue 是看到[谁在使用 / iView Users](https://github.com/iview/iview/issues/2143) 有感而發，不過 Tocas UI 本來也就有要收集使用者的打算了。收集到的網站會在之後丟至 Tocas UI 網站（順帶一提，Tocas UI 目前有[官方範例集](https://examples.tocas-ui.com/)）。

如果你的網站，或者作品有用上 Tocas UI（無論規模，就算是單頁小應用程式），透過下列格式在這裡回覆

```
專案名稱：Tocas UI
團隊或作者：Yami Odymel
連結：https://tocas-ui.com/
簡介（可選）：Tocas UI 是個可愛的介面資源庫，全世界不到 0.01% 的人都在使用最好用的 Tocas UI！
```

> 可以的話附上螢幕截圖讓別人參觀參觀。

---

_題外話：Tocas UI 2.4 會有很大的模組改進和新功能，盡請期待。_

**Comment by YamiOdymel** [comment]
一個可愛的範例呢⋯⋯就像這樣。

專案名稱：Konpf Managment
團隊或作者：SpeedLimit
連結：[http://speedlimit-hackathon.surge.sh/login](http://speedlimit-hackathon.surge.sh/login)
簡介（可選）：Konpf Managment 是基於黑客松下的產物，用以與追蹤裝置進行連動，可追蹤家人的所在並結合社群的概念。


![2017-05-06 6 39 33](https://user-images.githubusercontent.com/7308718/32034562-dde7beb4-b9d8-11e7-8883-d36e42fec7a8.png)

![2017-05-07 12 46 56](https://user-images.githubusercontent.com/7308718/32034569-e27df4a2-b9d8-11e7-98f6-66ec18822620.png)

**Comment by itshenrywu** [comment]
專案名稱：松農查詢系統
作者：[Henry Wu](https://henrywu.tw) , Secret
連結：已停止服務
簡介：使用爬蟲取得資料，將介面超恐怖的學生查詢系統優化，成為方便手機、平板、電腦使用的爬蟲。
![ts](https://user-images.githubusercontent.com/8154476/32047994-6e616070-ba7a-11e7-9ff3-b72b2a1fa241.png)

**Comment by gnehs** [comment]
專案名稱：Tocas Xiaoan
團隊或作者：@gnehs @itshenrywu
連結：https://xiaoan.tocas-ui.com/
簡介（可選）：洨洨安的歡樂天堂！
![image](https://user-images.githubusercontent.com/16719720/32054542-4b60afa6-ba91-11e7-8f0c-7b9c0b88f9f9.png)

**Comment by gnehs** [comment]
專案名稱：Anime-List
團隊或作者：@gnehs
連結：https://gnehs.github.io/Anime-List/
簡介（可選）：展示新番的清單
![image](https://user-images.githubusercontent.com/16719720/32054648-ad89c46a-ba91-11e7-8dde-d1f6ebb54b6d.png)

**Comment by toby3d** [comment]
專案名稱：toby3d
團隊或作者：@toby3d
連結：https://toby3d.me/
簡介（可選）：toby3d 😶
![default](https://user-images.githubusercontent.com/5412322/32056141-534cb462-ba7d-11e7-892d-96ce366adfda.png)

**Comment by lekoOwO** [comment]
專案名稱：CloudMusicAPI
團隊或作者：[@rextw](https://github.com/rexx0520) [@jixun](https://github.com/JixunMoe/)
連結：https://cm.rextw.com/
簡介（可選）：與朋友分享音樂！
![image](https://user-images.githubusercontent.com/20151124/32057872-192ebfb8-ba2e-11e7-8624-c7a014eed6aa.png)

**Comment by ombwp** [comment]
專案名稱：Meteor 板主票選即時得票數
作者：Henry Wu (https://omwu.me)
連結：https://omwu.me/bmVote/
簡介：統計投票文留言內容並顯示即時得票數
![c3d17gk](https://user-images.githubusercontent.com/8154476/32059184-ecbf4360-ba9d-11e7-8cfa-6ea219636cc1.png)

**Comment by t510599** [comment]
專案名稱：Online Web Editor
作者：Tony Yang, Stone APP Technology Studio. ([GitHub](https://github.com/stoneapptech))
連結：[https://app.stoneapp.tech/edtior](https://app.stoneapp.tech/edtior)
簡介：線上編輯網頁並預覽
![screencapture-app-stoneapp-tech-editor-1509090765042](https://user-images.githubusercontent.com/18533304/32093460-f0c9fb9e-bb2e-11e7-8041-8cd5bc14688f.png)
![screencapture-app-stoneapp-tech-editor-1509090758554](https://user-images.githubusercontent.com/18533304/32093459-f0a2ad82-bb2e-11e7-8a45-9b502ff0460b.png)

**Comment by hpcslag** [comment]
專案名稱：Hexo Theme - Morgan
團隊或作者：@hpcslag
連結：https://hpcslag.github.io/hexo-theme-morgan/demo/
簡介：一個 Hexo 主題，基於 Tocas UI。 

![](https://camo.githubusercontent.com/459e123eb43d9fc57fab32aa1a80270d9fb2f9a2/687474703a2f2f692e696d6775722e636f6d2f467041634163482e706e67)

**Comment by itshenrywu** [comment]
專案名稱：Meteor 學生社群
作者：[Henry Wu](https://henrywu.tw) ([Meteor](https://meteor.today))
連結：https://meteor.today
![image](https://user-images.githubusercontent.com/8154476/32112591-3f758ec0-bb70-11e7-9b94-de1163cf47fd.png)

**Comment by whl83111** [comment]
專案名稱：貨運查詢
團隊或作者：tommy1994111
連結：https://github.com/tommy1994111/delivery-status https://delivery-status-flask.herokuapp.com/
簡介（可選）：東風貨運、黑貓宅急便&速立達 查詢 前端為Vue.js 後端使用flask+爬蟲
![default](https://user-images.githubusercontent.com/17292342/32397822-b0785664-c126-11e7-93f8-63c2d6473b90.JPG)

**Comment by kahogeoff** [comment]
專案名稱：雲林文化力
團隊或作者：Geoffrey Cheung
連結：https://yuntech-web-demo.herokuapp.com/
簡介：一個功能齊全、然後給擱置掉的新聞網站專案, 使用Laravel(php)+MySQL

![screenshot-2017-11-8 -](https://user-images.githubusercontent.com/843571/32532825-e3da8090-c487-11e7-91e3-98849a0a3e68.png)

**Comment by racterub** [comment]
專案名稱：桃園高中成績查詢
團隊或作者：Racterub
連結：[https://tyshscore.herokuapp.com](https://tyshscore.herokuapp.com)
簡介：Based on Flask, 桃園高中成績查詢, 正在接圖表中.


![image](https://user-images.githubusercontent.com/20561837/45375369-53c1f500-b627-11e8-8a5e-64cff44245d5.png)

**Comment by gnehs** [comment]
專案名稱：Swore
團隊或作者：@TWScore
連結：https://twscore.ml/ [TWScore/Swore](https://github.com/TWScore/Swore)
簡介：可愛的查成績網站
![image](https://user-images.githubusercontent.com/16719720/35730042-8f820f42-084b-11e8-96d4-e2be5f13bb0e.png)

**Comment by JasonHK** [comment]
專案名稱：Countdown 2047
團隊或作者：[Jason Kwok](https://github.com/JasonHK)
連結：[http://github.jasonhk.net/Countdown-2047/](http://github.jasonhk.net/Countdown-2047/)
簡介：Countdown from now to Jul 1, 2047.
![Banner](https://user-images.githubusercontent.com/4410086/36296463-558bcae8-1328-11e8-875c-788409b323c1.png)
![Mockup](https://user-images.githubusercontent.com/4410086/36296507-813936e4-1328-11e8-8a7f-95380db317a4.jpeg)

**Comment by goodjack** [comment]
專案名稱：UQ 搜尋
團隊或作者：小克
連結：尚未完成，未上先貼
簡介：針對某品牌的價格、搭配做的查詢系統 :P
 
---
 
![uqsearch_v3](https://user-images.githubusercontent.com/1116129/39081916-8265083c-457c-11e8-83ab-c5995f1aa08b.png)
 
---
 
![uqsearch_v3_limited_offers](https://user-images.githubusercontent.com/1116129/39081918-83e04ac8-457c-11e8-9aa0-9383e90a0b66.png)

**Comment by cyliang** [comment]
專案名稱：台大Covart Lab網站
團隊或作者：Chih-Yung Liang
連結：https://covart.csie.ntu.edu.tw

![covart csie ntu edu tw_](https://user-images.githubusercontent.com/6300506/44993726-21cce500-afce-11e8-96bc-a4a06b923d0e.png)

**Comment by t510599** [comment]
專案名稱：INFOR 31st 官網
團隊或作者：[Tony Yang](https://github.com/t510599)
連結：[https://31.infor.org](https://31.infor.org)
簡介：建國中學資訊社第31屆官網

![default](https://user-images.githubusercontent.com/18533304/47960482-9eb12500-e038-11e8-8801-9fd2d1b34136.png)

**Comment by itshenrywu** [comment]
專案名稱：明志科大宿舍分機 / IP 查詢
作者：[Henry Wu](https://henrywu.tw)
連結：https://mcut.henrywu.tw/ip

**Comment by city8208** [comment]
專案名稱：Welljoy電商客戶留言板+網頁後台管理(串接Prestashop)
作者：張益誠
連結：http://welljoyus.com/index.php?id_cms=24&controller=cms&id_lang=2

<img src="https://i.imgur.com/BeE030Y.png" alt="default" style="max-width:100%;">

**Comment by tobychui** [comment]
專案名稱：ArOZ Online System
團隊或作者：Toby Chui feat. IMUS Laboratory
連結：http://aroz.online/ （需要自行架設）
簡介：Web Desktop 作業系統，提供基本的影音串流、離線下載、轉檔、文件處理、編程開發、檔案壓縮整理、集群及平衡運算等功能。使用 Tocas UI 2.3.x 作為系統標準 GUI 規范。
![2019-03-16_14-15-05](https://user-images.githubusercontent.com/24617523/54471624-f5084e80-47f6-11e9-95f5-b44d70e8443e.png)
![2019-03-16_14-12-20](https://user-images.githubusercontent.com/24617523/54471627-fa659900-47f6-11e9-944d-98d2a792b846.png)
![2019-03-16_14-12-56](https://user-images.githubusercontent.com/24617523/54471629-fcc7f300-47f6-11e9-872a-2791967b520b.png)
![2019-03-16_14-14-49](https://user-images.githubusercontent.com/24617523/54471630-fe91b680-47f6-11e9-9746-bcc747646d50.png)

**Comment by seadog007** [comment]
專案名稱：台灣抓漏小天使 Breach.tw
團隊或作者：海豹 ([seadog007](https://seadog007.work))、AIS3 2019 Web Group 1
連結：[breach.tw](https://breach.tw), [GitHub](https://github.com/seadog007/breach.tw)
簡介：A service that can track data breaches like "Have I Been Pwned", but it is specific for Taiwan. 本產品提供台灣（中華民國）之個資外洩事件查詢及追蹤服務。 讓使用者了解自己是否存在於重大資安外洩事件清單中，且增加使用者之資訊安全素養。

<img width="1680" alt="螢幕快照 2019-08-03 上午9 24 52" src="https://user-images.githubusercontent.com/5138409/63143662-62304200-c02a-11e9-9518-4b34a1a51f67.png">
<img width="1680" alt="螢幕快照 2019-08-16 下午1 33 32" src="https://user-images.githubusercontent.com/5138409/63143677-7411e500-c02a-11e9-92f9-05b53f15adba.png">

**Comment by oToToT** [comment]
專案名稱：JudgeGirl Scoreboard
團隊或作者：@oToToT
連結：https://www.csie.ntu.edu.tw/~b08902100/jgsb/ , https://github.com/oToToT/JudgeGirl-Scoreboard
簡介：A scoreboard for [JudgeGirl](https://judgegirl.csie.org) contest.
![image](https://user-images.githubusercontent.com/8341564/69824123-db544d80-1245-11ea-8a2d-369d6a882078.png)
![image](https://user-images.githubusercontent.com/8341564/69824162-ead39680-1245-11ea-8ee1-c6628274fd02.png)

**Comment by city8208** [comment]
專案名稱：WebCoding
團隊或作者：@Fred 誠
連結：https://akakaze.idv.tw/WebCoding/
           https://github.com/city8208/AsciiJS
           https://github.com/city8208/QRcodeJS

簡介：Creat Ascii Art & QRcode program more easily!!
關鍵的功能部分我都簡化優化過了，歡迎大家使用

![image](https://user-images.githubusercontent.com/43942467/78251890-965a6380-7524-11ea-8a4b-f6e94fb0ef96.png)

![image](https://user-images.githubusercontent.com/43942467/78252011-c4d83e80-7524-11ea-9723-1b23e6f8dafe.png)
