### ISSUE TITLE
新增 Flags，新的國旗元件

### ISSUE THREAD

**Issue by YamiOdymel** [teacat/tocas#525]
![2017-11-15 11 11 47](https://user-images.githubusercontent.com/7308718/32816851-729038f0-c980-11e7-92cf-b1615ef3eae6.png)

並且搭配 SVG Flags：https://github.com/lipis/flag-icon-css

還有大小設置。

**Comment by itshenrywu** [comment]
看來載入會變更久了。

**Comment by YamiOdymel** [comment]
應該是還好啦⋯⋯畢竟圖片是用到的時候才會讀取
