### ISSUE TITLE
<ol> 的部份屬性沒有作用

### ISSUE THREAD

**Issue by iigmir** [teacat/tocas#528]
在 HTML5，可以透過屬性、更改有序清單的外觀如從哪裡開始（`start`）、用什麼單位（`type`）、甚至還有方向(`reversed`)。詳細的屬性可以參考 [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ol)。
這些都是 HTML5 有的，但是在 TocasUI，有序清單大都只能照著原樣顯示、而無法透過屬性更改。如果我用 `.unstyled` 的話，又不成了：它甚至連列表的樣式都不像。

這方面有興趣解決嗎？

**Comment by YamiOdymel** [comment]
> 「如果我用 `.unstyled` 的話，又不成了：它甚至連列表的樣式都不像。」

原因我想是因為 Tocas 有用上 `reset.css` 的重設樣式表把 `.unstyled` 之後的原生清單搞得四不像。

---

這部分有點棘手，有幾個做法跟其問題：

1. 取消 Tocas 覆蓋原生標籤和 Reset，讓 HTML5 標籤回歸正常不要被 Tocas 化。（#518）
    * **解決**：
        1. `ol` 可以正常使用 `reversed`、`start`、`type`。
    * **問題**：
        1. 原生標籤沒有 Tocas 樣式，會跟其他 Tocas 元件外觀不協調。
        2. 部分 WordPress 主題會有障礙（主題不能幫 `h1`～`h6` 等標籤加上 Tocas 樣式名稱）。

2. 讓 Tocas 的清單支援 `reversed`、`start`、`type`。
    * **解決**：
        1. `ol` 可以正常使用 `reversed`、`start`、`type`。
        2. 原生標籤保有 Tocas 統一的樣式。
    * **問題**：
        1. 這方面單靠 CSS 做不到，需要 JavaScript（所以每次清單有異動，就需要呼叫 JavaScript）。

---

我還想不出這方面該怎麼處理，你提供看看有什麼想法。也許我應該去看一下 Bootstrap 是怎麼解決的。

**Comment by iigmir** [comment]
嗯…我在想的是，掛上 `.unstyled` 後才讓 HTML5 標籤回歸正常，或是掛上特定 Class 才啟動 JavaScript 以便 Tocas 的清單支援 `reversed`、`start`、`type`。
……不過我總覺得這些方法不現實。真是如此，那我會偏向 1。

Semantic-UI 好像也有類似問題。
https://github.com/Semantic-Org/Semantic-UI/issues/2802

**Comment by YamiOdymel** [comment]
@gnehs 你有沒有什麼想法？

如果取消原生標籤支援，以後有關 WordPress 的佈景主題就要在頁面載入後自動替 `h1` ~ `h6` 標籤加上 `ts header` 了（還有一些 `blockquote` 什麼的）。

**Comment by gnehs** [comment]
如果拿掉的話我應該拿 js 加或我自幹 CSS 吧
幹我覺得會搞出 Tocas UI for WordPress 
畢竟 NAV 也不是 Tocas UI 的格式

**Comment by gnehs** [comment]
覺得可以直接替 Body 之類的大標籤加上 unstyled 的 class 來禁用整個頁面的 CSS 原生標籤支援
