### ISSUE TITLE
對話氣泡 "右側對話" 在Chrome 失效

### ISSUE THREAD

**Issue by WingCH** [teacat/tocas#531]
https://tocas-ui.com/views/speeches/#右側對話

對話氣泡 "右側對話" 在Chrome 會在左側

已分別在Windown 和 mac 的 Chrome測試

在mac的Safari能正常運作

**Comment by WingCH** [comment]
![2017-11-25 at 10 16](https://user-images.githubusercontent.com/19588517/33231321-5d20fbc4-d22e-11e7-8c6d-ad45def9230c.png)

**Comment by YamiOdymel** [comment]
有趣，目前的 Chrome 正式版確實有這個問題（Chrome 52），不過到了 Chrome 54 就被修正了。等待 Google 釋出新版本的 Chrome 應該就能解決這個奇異的鳥問題。

![2017-11-25 10 25 23](https://user-images.githubusercontent.com/7308718/33231390-cc6f962e-d22f-11e7-92d8-bd4fb5628f71.png)

![2017-11-25 10 26 06](https://user-images.githubusercontent.com/7308718/33231392-ce3c3584-d22f-11e7-9311-fa4e5c28bb4a.png)

![2017-11-25 10 26 27](https://user-images.githubusercontent.com/7308718/33231393-cff5f48c-d22f-11e7-94e2-11147e903ba5.png)

**Comment by WingCH** [comment]
多謝幫忙xd

**Comment by gnehs** [comment]
Chrome 66 復活ㄌ
![default](https://user-images.githubusercontent.com/16719720/39957403-3228d68c-5625-11e8-9176-87be12b8a9eb.png)

![default](https://user-images.githubusercontent.com/16719720/39957398-1db339ae-5625-11e8-859a-70a926932338.png)
