### ISSUE TITLE
In slate buttons overlap each other

### ISSUE THREAD

**Issue by toby3d** [teacat/tocas#536]
[Example code](https://tocas-ui.com/try/?html=%3C!--%3Cheader%20class=%22ts%20big%20heading%20slate%22%3E--%3E%5Cn%20%20%20%20%3Cdiv%20class=%22ts%20center%20aligned%20basic%20fitted%20segment%22%3E%5Cn%20%20%20%20%20%20%20%20%3Cdiv%20class=%22ts%20relaxed%20separated%20stackable%20buttons%22%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%3Ca%20class=%22ts%20secondary%20opinion%20button%22%20href=%22//t.me/MyPackBot%22%3EOpen%20@MyPackBot%3C/a%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%3Ca%20class=%22ts%20link%20image%20button%22%20href=%22//patreon.com/bePatron?c=243288%22%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cimg%20src=%22//toby3d.github.io/TeLetterBot/static/patreon.png%22%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%3C/a%3E%5Cn%20%20%20%20%20%20%20%20%3C/div%3E%5Cn%20%20%20%20%3C/div%3E%5Cn%3C!--%3C/header%3E--%3E):
```
<header class="ts big heading slate">
    <div class="ts center aligned basic fitted segment">
        <div class="ts relaxed separated stackable buttons">
            <a class="ts secondary opinion button" href="//t.me/MyPackBot">Open @MyPackBot</a>
            <a class="ts link image button" href="//patreon.com/bePatron?c=243288">
                <img src="//toby3d.github.io/TeLetterBot/static/patreon.png">
            </a>
        </div>
    </div>
</header>
```

If comment `<header>` element, then (almost) all works fine.

**Comment by YamiOdymel** [comment]
Not sure when, but this is already fixed in 2.4, so nothing to change.

Note to myself:

```sass
//-------------------//
//   Image & Embed
//-------------------//

.ts.slate .image:not(i):not(.ts),
.ts.slate .video:not(i)
    +extend(no-select)

    left    : 0
    top     : 0
    right   : 0
    bottom  : 0
    overflow: hidden
    position: absolute

    pointer-events: none
```
