### ISSUE TITLE
近期会提供相关对 React 的支持吗？

### ISSUE THREAD

**Issue by Kilerd** [teacat/tocas#537]
你好，我打算用这个UI库设计界面，但是似乎并没有 React 的支持。

请问，你们在近期又打算出相关的 React 元件库吗？

**Comment by YamiOdymel** [comment]
我自己本身是寫 Vue，而沒寫過 React。不過在寫 Vue 的時候原本也有意將 Tocas 做成類似 Vue UI Library，但後期發現這樣反倒會**綁手綁腳**、自訂上**更有困難**。

因為被寫成制式化的 UI Component 了會有下列困擾：

1. **不方便**隨需要時更改 Style。
2. **沒辦法**隨心所欲地使用 `top attached` 這種高自訂化的拼接樣式。

這個問題已經有前車之鑑了：[Semantic UI React](https://react.semantic-ui.com)。

除了 Model 可以與 Vue、React 雙向綁定外，我個人是想不太到有什麼優勢（歡迎提供看法？）。

個人建議如果有需要，可以自行將相關元素組合手動成 UI Component。我目前使用 Vue + Tocas UI（自行將需要的地方手動包成 Component）是沒有遇到什麼問題。

![2016-11-10 4 04 35](https://user-images.githubusercontent.com/7308718/33489304-793a7a6e-d6ee-11e7-897a-0f98daf6847e.png)
