### ISSUE TITLE
新增類似 Facebook 貼文讀取時的 Placeholder

### ISSUE THREAD

**Issue by YamiOdymel** [teacat/tocas#538]
https://github.com/michalsnik/vue-content-placeholders

![](https://camo.githubusercontent.com/c1aad1a0b2ff76b16bade98b3a30afe708920078/68747470733a2f2f692e696d6775722e636f6d2f4a516c466a73532e676966)

---

接下來該討論用法，因為不是 Component，所以不好一次就生成幾個 Lines。

也許可能像這樣？

```html
<div class="ts placeholder">
    <div class="header">
        <div class="image"></div>
        <div class="text"></div>
        <div class="text"></div>
    </div>
    <div class="text"></div>
    <div class="text"></div>
    <div class="text"></div>
</div>
```

![](https://camo.githubusercontent.com/0260507b86d18092c62dc2646ea737afb9d2976c/68747470733a2f2f692e696d6775722e636f6d2f4c5766717855652e706e67)

---

```html
<div class="ts rounded placeholder">
    <div class="image"></div>
    <div class="header text"></div>
    <div class="text"></div>
</div>
```

![](https://camo.githubusercontent.com/2ce2780ffb1ea3576277b49ce6531a0901b3b592/68747470733a2f2f692e696d6775722e636f6d2f4e4262365a42372e706e67)

---

如果搭配上 `:after` 跟 `:before`，也許可以簡化成⋯⋯。

```html
<div class="ts placeholder">
    <div class="header">
        <div class="image"></div>
        <div class="texts"></div>
    </div>
    <div class="texts"></div>
</div>
```

**Comment by YamiOdymel** [comment]
最終考慮的用法如下，搭配 After 與 Before 看起來是個好想法。

# Example

![2017-12-12 8 14 39](https://user-images.githubusercontent.com/7308718/33884062-3298668c-df79-11e7-93d9-5fa08814d6de.png)


```html
<div class="ts placeholder">
    <div class="image header"></div>
    <div class="texts"></div>
    <div class="text"></div>
</div>
```

&nbsp;

# Headers

![2017-12-12 8 08 04](https://user-images.githubusercontent.com/7308718/33883805-3d2e1412-df78-11e7-92be-294ff9c165fe.png)

```html
<div class="image header"></div>
```

---

![2017-12-12 8 09 31](https://user-images.githubusercontent.com/7308718/33883851-6afeefec-df78-11e7-968b-e2f57d65080d.png)

```html
<div class="text header"></div>
```

&nbsp;

# Texts

![2017-12-12 8 09 36](https://user-images.githubusercontent.com/7308718/33883867-78eed87e-df78-11e7-83eb-5262c53d43d7.png)

```html
<div class="texts"></div>
```

---

![2017-12-12 8 10 34](https://user-images.githubusercontent.com/7308718/33883908-94a67d74-df78-11e7-8137-e334a748fcae.png)

```html
<div class="text"></div>
```

&nbsp;

# Elements

![2017-12-12 8 13 02](https://user-images.githubusercontent.com/7308718/33883991-ea19142e-df78-11e7-8261-ebfa68527c73.png)

```html
<div class="image"></div>
```

**Comment by toby3d** [comment]
Maybe add `.determinate` class for blink animation?

**Comment by YamiOdymel** [comment]
@toby3d  Of course I'd like to, but ... it's **impossible** with a simple structure as above.

[This example](https://codepen.io/Mestika/pen/ByNYBa) has the _blink_ animation but they use a different approach. They creates **a lot** of the white divs as the masks. So the placeholders share the same blink effect.

![2017-12-12 9 51 53](https://user-images.githubusercontent.com/7308718/33888061-d5d9421e-df86-11e7-9053-23866368fc3f.png)

**Comment by YamiOdymel** [comment]
Okay I was wrong, I think the blink animation is possible now.

![2017-12-13 12 38 22](https://user-images.githubusercontent.com/7308718/33896512-f300a8ca-df9d-11e7-898c-7e64f0636b79.png)

**Comment by toby3d** [comment]
Yaay! :3
