### ISSUE TITLE
新增 Circular Progress 圓形進度條

### ISSUE THREAD

**Issue by YamiOdymel** [teacat/tocas#539]
且還要能支援中間擺放數字或是 `statistics` 和 `icon` 元件。

https://mega.nz/fm/dashboard

![2017-12-06 4 39 54](https://user-images.githubusercontent.com/7308718/33652443-72a905e4-daa4-11e7-8ad2-83310c9f8b89.png)

---

https://www.iviewui.com/components/circle

![2017-12-06 4 42 04](https://user-images.githubusercontent.com/7308718/33652448-7794ed98-daa4-11e7-964d-857f2a948a71.png)

**Comment by yeungalan** [comment]
會不會有javascript 函式使圓形進度條更新時出現動畫效果?
例子:
http://jsfiddle.net/andsens/mLA7X/
