### ISSUE TITLE
No styles for file-input?

### ISSUE THREAD

**Issue by toby3d** [teacat/tocas#541]
![default](https://user-images.githubusercontent.com/5412322/33715493-917c4f96-db74-11e7-90c3-a3411cfb91e9.png)
```html
<h4>Upload image or icon (jpg, jpeg, png)</h4>
<div class="ts input">
  <input name="fileUpload" type="file">
</div>
```

**Comment by YamiOdymel** [comment]
File Input doesn't support in Tocas(#274), and you'll have to move it out from the `.ts.input` div. 

Because it's hard to modify the styles of the file input since every browser and device has it's own weird rendering style.
