### ISSUE TITLE
Separated Buttons 在 Card 的 Last Child 會沒有右邊框

### ISSUE THREAD

**Issue by YamiOdymel** [teacat/tocas#542]
下面這行 CSS 的影響。

```css
.ts.card .buttons .button:last-child {
    border-right: 0;
}
```

![2017-12-10 1 43 48](https://user-images.githubusercontent.com/7308718/33802352-35401382-ddb0-11e7-8bdf-4d1ab6b47c45.png)

```html
<div class="right aligned secondary extra content">
    <div class="ts separated buttons">
        <button class="ts link button">
            <h4>NT$790</h4>
        </button>
        <a class="ts negative basic labeled icon button" href="http://www.uniqlo.com/tw/store/goods/400332" target="_blank">
            <i class="external link icon"></i> 前往官網
        </a>
    </div>
</div>
```

**Comment by goodjack** [comment]
欸？我要回報的不是這個
我看到的畫面不一樣

這個是 Card
![image](https://user-images.githubusercontent.com/1116129/33802706-ac97c7c0-ddb7-11e7-8ad5-e14dabe1e956.png)

這個是 Segment
![image](https://user-images.githubusercontent.com/1116129/33802702-a4a938a0-ddb7-11e7-9b8d-e7b73324fe6f.png)

NT$790 在 Card 會偏上，而且跟按鈕的間距怪怪的
另外，看起來陰影的呈現也跟你截圖的不一樣

**Comment by goodjack** [comment]
補一下環境
macOS 10.12.6
Chrome 63.0.3239.84 (正式版本) beta (64 位元)

**Comment by YamiOdymel** [comment]
@goodjack 在你給的 Codepen  範例中，Card 的用法是：

```html
<div class="right aligned secondary extra content">
    <button class="ts link button">
        <h4>NT$790</h4>
    </button>
    <a href="http://www.uniqlo.com/tw/store/goods/400332" target="_blank">
        <button class="ts negative basic labeled icon button">
            <i class="external link icon"></i> 前往官網
        </button>
    </a>
</div>
```

跟你在 Segment 的用法有差異，所以我修正改成了：

```html
<div class="right aligned secondary extra content">
    <div class="ts separated buttons">
        <button class="ts link button">
            <h4>NT$790</h4>
        </button>
        <a class="ts negative basic labeled icon button" href="http://www.uniqlo.com/tw/store/goods/400332" target="_blank">
            <i class="external link icon"></i> 前往官網
        </a>
    </div>
</div>
```

然後就發現了這個可愛的 Issue。

**Comment by goodjack** [comment]
哦哦哦
被你這樣一說我好像有遇到這個
以為是用法不同所以就改成跟範例一樣了

**Comment by goodjack** [comment]
改成跟你寫的一樣之後
間距跟高度都對了 但是左側線也不見了
![image](https://user-images.githubusercontent.com/1116129/33811484-11b96f36-de4f-11e7-8bdd-1f14ec649bfe.png)

---

20171227 更新：
我沒改到 a > button
把 button 樣式套到 a 之後就只有右側線不見了
