### ISSUE TITLE
分隔線沒有顯示或顯示不正常

### ISSUE THREAD

**Issue by goodjack** [teacat/tocas#543]
示範頁面
https://codepen.io/goodjack/pen/YEmRpq

其中的段落
```html
  <br>
  <div class="ts section divider"></div>
  <br>
  <div class="ts horizontal divider">我是分隔線</div>
  <br>
  <div class="ts divider"></div>
  <br>
```

我看到的內容是
![image](https://user-images.githubusercontent.com/1116129/33803138-8a09bdc4-ddc3-11e7-974c-1cd2a184bbef.png)

只有第二個有出現，而且中文字偏上

環境：
- macOS 10.12.6
- Chrome 63.0.3239.84 (正式版本) beta (64 位元)

**Comment by goodjack** [comment]
Safari 11.0.2（12604.4.7.1.4）
![image](https://user-images.githubusercontent.com/1116129/33803166-fd37c926-ddc3-11e7-92ff-c8e308124de2.png)

Firefox 57.0.1 (64 位元)
![image](https://user-images.githubusercontent.com/1116129/33803174-52d11c0c-ddc4-11e7-8a6c-424b094d529f.png)

**Comment by YamiOdymel** [comment]
看起來是範例的使用方式過於奇異。在網格系統（`.ts.grid`）中只可以擺放欄位（`.column`）、行（`.row`），其他元素必須擺置於欄位（`.column`）中。

> 這意味著標題、卡片、分隔線都必須放入於欄位中。

在你提供的範例內，有許多不應該出現在網格系統（`.ts.grid`）內的元素，將分隔線（`.divider`）從網格系統內移出就能解決這個問題。

舉例來說：

```html
<div class="ts narrow container relaxed grid">
  <div class="ts horizontal divider">我是分隔線</div>
</div>
```

正確來說應該是：

```html
<div class="ts narrow container relaxed grid">
    <div class="column">
        <div class="ts horizontal divider">我是分隔線</div>
    </div>
</div>
```
