### ISSUE TITLE
Strange width in .sidebar.menu > .item > .input

### ISSUE THREAD

**Issue by toby3d** [teacat/tocas#548]
[Example code:](https://tocas-ui.com/try?html=%3Cdiv%20class=%22ts%20visible%20static%20vertical%20menu%20sidebar%22%3E%5Cn%20%20%3Cdiv%20class=%22basic%20item%22%3E%5Cn%20%20%20%20%3Cdiv%20class=%22ts%20fluid%20right%20icon%20input%22%3E%5Cn%20%20%20%20%20%20%3Cinput%20type=%22search%22%20placeholder=%22Search%22%3E%5Cn%20%20%20%20%20%20%3Ci%20class=%22search%20icon%22%3E%3C/i%3E%5Cn%20%20%20%20%3C/div%3E%5Cn%20%20%3C/div%3E%5Cn%3C/div%3E)
```html
<div class="ts visible static vertical menu sidebar">
  <div class="basic item">
    <div class="ts fluid right icon input">
      <input type="search" placeholder="Search">
      <i class="search icon"></i>
    </div>
  </div>
</div>
```

Result:
![default](https://user-images.githubusercontent.com/5412322/33825980-3ced89f4-de85-11e7-8bc7-f69cb4b8044b.png)

- This can be fixed by setted `input` style to `width: 140px` (if sidebar width 230px);
- Looks fine if sidebar width >300px by adding `.wide` or `.very.wide` classes;
- Looks bad if sidebar width <300px by adding `.thin` or `.very.thin` classes;

**Comment by YamiOdymel** [comment]
I don't see any problem with the code you provided and the example. 

Maybe it's the browser bug and it might been fixed already?

![2018-03-29 10 25 43](https://user-images.githubusercontent.com/7308718/38094395-34804ff2-33a0-11e8-9dd0-1f6f0cf01865.png)

**Comment by toby3d** [comment]
![default](https://user-images.githubusercontent.com/5412322/38097963-31995636-3390-11e8-9af4-5e04e651ef4e.png)
Same [result in playground](https://tocas-ui.com/try?html=%3Cdiv%20class=%22ts%20visible%20static%20vertical%20menu%20sidebar%22%3E%5Cn%20%20%3Cdiv%20class=%22basic%20item%22%3E%5Cn%20%20%20%20%3Cdiv%20class=%22ts%20fluid%20right%20icon%20input%22%3E%5Cn%20%20%20%20%20%20%3Cinput%20type=%22search%22%20placeholder=%22Search%22%3E%5Cn%20%20%20%20%20%20%3Ci%20class=%22search%20icon%22%3E%3C/i%3E%5Cn%20%20%20%20%3C/div%3E%5Cn%20%20%3C/div%3E%5Cn%3C/div%3E) today. :thinking:
