### ISSUE TITLE
[建議] 搜尋引擎友善的文件

### ISSUE THREAD

**Issue by goodjack** [teacat/tocas#560]
似乎無法用 Google 搜尋到文件的內容
找一個功能通常都需要在文件的各大分類裡來回切換

**Comment by YamiOdymel** [comment]
這個問題確實很明顯，主要是目前的文件採用 Vue.js，而 Vue.js 是 Client Side Render 會讓搜尋引擎不方便產生索引。

在近期將推出的 2.4 會以 Markdown 產生靜態 HTML 為主，並解決圖示說明頁面卡死的問題，還有更改排版、增加一個側邊欄，這樣就不需要整天找元件了。

**Comment by gnehs** [comment]
我覺得需要搜尋功能
