### ISSUE TITLE
Basic Button 的 脈動動畫

### ISSUE THREAD

**Issue by t510599** [teacat/tocas#562]
希望用basic button的時候 也能有 看的見的 脈動效果(平常狀態背景是透明)

**Comment by t510599** [comment]
`.ts.pulsing.basic.button::before { border-color: inherit; border: 1.5px solid; }`
或許這樣(?
Demo : [https://jsfiddle.net/nnkkn3jv/](https://jsfiddle.net/nnkkn3jv/)

**Comment by YamiOdymel** [comment]
感覺還不錯，會修改
