### ISSUE TITLE
像 Material Design 般的高彩度顏色

### ISSUE THREAD

**Issue by goodjack** [teacat/tocas#565]
現在提供的語意比較像大地色風格

請問顏色的部分能否提供像 Material Design 系列的高彩度色
讓網站或 app 看起來比較現代感？

**Comment by YamiOdymel** [comment]
基本上是不會新增其他顏色了，畢竟[最重要的「顏色」就是網頁的內容](https://ant.design/docs/spec/colors-cn)。

![2017-12-21 3 41 58](https://user-images.githubusercontent.com/7308718/34245602-94294e6e-e665-11e7-846d-0a19b794a34f.png)

不過最近在寫 2.4 文件的時候，有意圖要建立一個 Theme Editor（_簡單說就是幫你改顏色變數然後編譯的產生器_），但是這樣的話就需要架後端啦——。

**Comment by goodjack** [comment]
我當然不是說要整個網站花花綠綠 🤣
但是 Ant 他們的功能色也是比較亮呢
我覺得這種黃色、紅色 比較有警示的作用

Theme Editor 是指類似這種嗎
http://getbootstrap.com/docs/3.3/customize/

**Comment by YamiOdymel** [comment]
@goodjack 類似那種沒錯，不過看起來很像在研究火箭科學，所以我想簡化成能調整基本色就好了。

Tocas 現在的顏色都是來自[基本色](https://github.com/TeaMeow/TocasUI/blob/master/src/modules/_colors.sass)，然後自動做顏色異動的。

不過 Theme Editor 實際做出來顏色成效好不好就不太清楚了。

**Comment by goodjack** [comment]
這裡有個新的開源服務可以參考
- https://pikock.github.io/bootstrap-magic/
- https://bootstrap.build/
