### ISSUE TITLE
Centered Menu 和 right menu 同時使用

### ISSUE THREAD

**Issue by t510599** [teacat/tocas#566]
![center menu](https://user-images.githubusercontent.com/18533304/34320242-1640b81c-e830-11e7-84a0-0a32d6621722.png)
被推到左邊去了

**Comment by YamiOdymel** [comment]
你期望看到的效果是哪種呢？全部置中嗎？

**Comment by t510599** [comment]
![default](https://user-images.githubusercontent.com/18533304/34320273-2ac880c0-e831-11e7-93e5-c95629344c9e.png)
大概這樣

**Comment by t510599** [comment]
![default](https://user-images.githubusercontent.com/18533304/34320426-333e472c-e835-11e7-9f57-61de5fb5f272.png)
順道一提 這條線也很怪

**Comment by YamiOdymel** [comment]
@t510599 那條線是 CSS 先天性的限制，沒辦法自動在最結尾省去。

倘若省去，也會在選單縮減的時候跟右邊的項目黏在一起而沒有分隔線。

**Comment by goodjack** [comment]
右邊不能省的話 如果左邊多一條呢？

**Comment by t510599** [comment]
`.ts.centered.menu > .item:last-of-type {  border-right:none;  }`  
`.ts.centered.menu .right.menu {  border-left:1px solid rgb(233,233,233);  }`  
試試(?
preview:  
![default](https://user-images.githubusercontent.com/18533304/34335014-91f433a6-e986-11e7-880b-bcbd0695ad3b.png)

**Comment by YamiOdymel** [comment]
@t510599 如果你的 `<a class="item">` 改為 `<div class="item">` 那條線會照常出現。

**Comment by t510599** [comment]
可是menu正常使用下不會有這種情況吧🤔

**Comment by YamiOdymel** [comment]
已經以你提供的方式將 `.right.menu` 以 `display: absolute` 修正（雖然這麼修有點治標不治本）。

至於邊線則沒有異動，因為 `last-of-type` 不可靠。有可能會在 `div` 跟 `a` 混搭的時候觸發導致在非最後面的元素右邊線消失。

**Comment by t510599** [comment]
![screenshot_20180118-203307 2](https://user-images.githubusercontent.com/18533304/35098462-36236f6c-fc8f-11e7-9821-2aca43bfb335.png)
關於邊線的部分 依 @goodjack 的建議在左邊加上線 看起來比較不會有不對稱的感覺

**Comment by YamiOdymel** [comment]
左邊加上線確實比較不會有「不對稱」的感覺，但是這樣就變成會跟 Menu 左外框線相衝，視窗寬度縮小的話左邊就會像是 2px 框線那樣⋯

或者也可以限定只在 `.centered.menu` 的時候這麼做，然後祈禱使用者不會把視窗縮小⋯🤔

**Comment by t510599** [comment]
還有 `position:absolute` 只是暫時在不考慮適應性的情況下所加的設定
如果太窄的話會很悲劇 就像這樣 擠成一坨：
![screenshot_20180118-210127 2](https://user-images.githubusercontent.com/18533304/35099431-eea06e02-fc92-11e7-88d9-92d29f44201c.png)

**Comment by YamiOdymel** [comment]
對，基本上就只能推薦不要在使用 `.centered.menu` 的時候用上 `.right.menu`。
