### ISSUE TITLE
Centered menu 在小寬度下 顯示異常

### ISSUE THREAD

**Issue by t510599** [teacat/tocas#567]
[TocasUI遊樂場](https://tocas-ui.com/try/?html=%3Cdiv%20style%3D%22width%3A100px%22%3E%5Cn%20%20%20%20%3Cdiv%20class%3D%22ts%20horizontally%20scrollable%20centered%20menu%22%3E%5Cn%20%20%20%20%20%20%20%20%3Ca%20class%3D%22item%22%3Etest%3C%2Fa%3E%5Cn%20%20%20%20%20%20%20%20%3Ca%20class%3D%22item%22%3Etest%3C%2Fa%3E%5Cn%20%20%20%20%20%20%20%20%3Ca%20class%3D%22item%22%3Etest%3C%2Fa%3E%5Cn%20%20%20%20%3C%2Fdiv%3E%5Cn%3C%2Fdiv%3E)
![default](https://user-images.githubusercontent.com/18533304/34335553-a69c0f50-e98a-11e7-902d-79d354f1f75f.png)

**Comment by YamiOdymel** [comment]
確實有這個問題，因為置中選單會從中間開始（一般是從左開始），所以才會遮蔽兩側的元素。

用 Flexbox 置中有這個問題還要想想怎麼解決。

**Comment by YamiOdymel** [comment]
這個問題直到 `justify-content: safe center` 出來之前都沒辦法修正（[請參閱 Stackoverflow](https://stackoverflow.com/questions/47635911/how-to-use-safe-center-with-flexbox)），因此延後。

**Comment by YamiOdymel** [comment]
順帶一提這個功能（`horizontally scrollable`）有可能會被拿掉（請參閱 #576）。
