### ISSUE TITLE
卡片在被 hover 時，語意有問題

### ISSUE THREAD

**Issue by goodjack** [teacat/tocas#568]
[Tocas 遊樂場](https://tocas-ui.com/try/?html=%3Cdiv%20class=%22ts%20doubling%20link%20cards%20four%22%3E%5Cn%20%20%20%20%3Ca%20class=%22ts%20inverted%20negative%20card%22%20href=%22#%22%3E%5Cn%20%20%20%20%20%20%20%20%3Cdiv%20class=%22image%22%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%3Cimg%20src=%22https://tocas-ui.com/assets/img/15d7510.png%22%3E%5Cn%20%20%20%20%20%20%20%20%3C/div%3E%5Cn%20%20%20%20%20%20%20%20%3Cdiv%20class=%22content%22%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%3Cdiv%20class=%22header%22%3ETocas%20Collection%3C/div%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%3Cdiv%20class=%22meta%22%3E@ts_collection%3C/div%3E%5Cn%20%20%20%20%20%20%20%20%3C/div%3E%5Cn%20%20%20%20%3C/a%3E%5Cn%20%20%20%20%3Ca%20class=%22ts%20negative%20card%22%20href=%22#%22%3E%5Cn%20%20%20%20%20%20%20%20%3Cdiv%20class=%22image%22%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%3Cimg%20src=%22https://tocas-ui.com/assets/img/15d7510.png%22%3E%5Cn%20%20%20%20%20%20%20%20%3C/div%3E%5Cn%20%20%20%20%20%20%20%20%3Cdiv%20class=%22content%22%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%3Cdiv%20class=%22header%22%3ETocas%20Collection%3C/div%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%3Cdiv%20class=%22meta%22%3E@ts_collection%3C/div%3E%5Cn%20%20%20%20%20%20%20%20%3C/div%3E%5Cn%20%20%20%20%3C/a%3E%5Cn%3C/div%3E)

```html
<div class="ts doubling link cards four">
    <a class="ts inverted negative card" href="#">
        <div class="image">
            <img src="https://tocas-ui.com/assets/img/15d7510.png">
        </div>
        <div class="content">
            <div class="header">Tocas Collection</div>
            <div class="meta">@ts_collection</div>
        </div>
    </a>
    <a class="ts negative card" href="#">
        <div class="image">
            <img src="https://tocas-ui.com/assets/img/15d7510.png">
        </div>
        <div class="content">
            <div class="header">Tocas Collection</div>
            <div class="meta">@ts_collection</div>
        </div>
    </a>
</div>
```

滑鼠指上去的時候
一般語意和反色語意都會受到影響
是被陰影蓋掉？

![image](https://user-images.githubusercontent.com/1116129/34354828-f8f3282e-ea6b-11e7-8095-8cd2126c963f.png)

![image](https://user-images.githubusercontent.com/1116129/34354833-02a4ff82-ea6c-11e7-88fe-6e1634da0d1d.png)

**Comment by goodjack** [comment]
[遊樂場的分享 link 好像是壞掉的](https://tocas-ui.com/try/?html=%3Cdiv%20class=%22ts%20doubling%20link%20cards%20four%22%3E%5Cn%20%20%20%20%3Ca%20class=%22ts%20inverted%20negative%20card%22%20href=%22#%22%3E%5Cn%20%20%20%20%20%20%20%20%3Cdiv%20class=%22image%22%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%3Cimg%20src=%22https://tocas-ui.com/assets/img/15d7510.png%22%3E%5Cn%20%20%20%20%20%20%20%20%3C/div%3E%5Cn%20%20%20%20%20%20%20%20%3Cdiv%20class=%22content%22%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%3Cdiv%20class=%22header%22%3ETocas%20Collection%3C/div%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%3Cdiv%20class=%22meta%22%3E@ts_collection%3C/div%3E%5Cn%20%20%20%20%20%20%20%20%3C/div%3E%5Cn%20%20%20%20%3C/a%3E%5Cn%20%20%20%20%3Ca%20class=%22ts%20negative%20card%22%20href=%22#%22%3E%5Cn%20%20%20%20%20%20%20%20%3Cdiv%20class=%22image%22%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%3Cimg%20src=%22https://tocas-ui.com/assets/img/15d7510.png%22%3E%5Cn%20%20%20%20%20%20%20%20%3C/div%3E%5Cn%20%20%20%20%20%20%20%20%3Cdiv%20class=%22content%22%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%3Cdiv%20class=%22header%22%3ETocas%20Collection%3C/div%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%3Cdiv%20class=%22meta%22%3E@ts_collection%3C/div%3E%5Cn%20%20%20%20%20%20%20%20%3C/div%3E%5Cn%20%20%20%20%3C/a%3E%5Cn%3C/div%3E)

**Comment by YamiOdymel** [comment]
這兩個問題分別是：
* [當移動到語意 Link Card 時，底線顏色會消失（被覆蓋）](https://github.com/TeaMeow/TocasUI/issues/494)
* [遊樂場中 href="#" 會因為 # 而阻斷分享連結](https://github.com/TeaMeow/TocasUI/issues/428)
