### ISSUE TITLE
Table 无法根据数据类型排列

### ISSUE THREAD

**Issue by Tex-Tang** [teacat/tocas#572]
这是我用于的PHP代码
```
// check a sample value
var sampleval = this.latestreport[0][col]

// true then reverse
this.sortcol = !this.sortcol

// Sort number
var sampleval = this.latestreport[0][col]
this.sortcol = !this.sortcol
// Sort number
if(!isNaN(sampleval)){
    this.latestreport.sort(function(a,b) {
        return a[col] - b[col]
    });
}

// Sort datetime
else if(new Date(sampleval).getTime()){
    this.latestreport.sort(function(a,b){
        return new Date(b.date) - new Date(a.date);
    });
}

// Sort alphabetically
else{
    this.latestreport.sort(function(a,b){
        return (a[col] < b[col]) ? -1 : 1;
    });
}

// reverse
if(this.sortcol){
    this.latestreport.reverse()
}
```
![image](https://user-images.githubusercontent.com/14901260/34912744-dcf0492e-f923-11e7-81aa-95583399c3c4.png)

无法排列整数类型

![image](https://user-images.githubusercontent.com/14901260/34912752-f7036e72-f923-11e7-8460-f5ea4f125c38.png)
无法排列整数+逗号类型

![image](https://user-images.githubusercontent.com/14901260/34912761-0e0e22c4-f924-11e7-8bae-2fe2d7f5033c.png)
无法排列日期

**Comment by coin3x** [comment]
也許還能讓 ts().tablesort() 能夠傳個 function 進去來自訂排序？ 🤔

**Comment by Tex-Tang** [comment]
我觉得可以，如果用户没有传任何函数，就以字符串来排列。

但这对有些用户来说并不友好。
