### ISSUE TITLE
在 Safari 瀏覽器中 Tab無法切換

### ISSUE THREAD

**Issue by t510599** [teacat/tocas#578]
在其他瀏覽器上面沒發生這種情況
發生問題的 code : [https://github.com/stoneapptech/webeditor](https://github.com/stoneapptech/webeditor)
![](https://user-images.githubusercontent.com/18533304/34978434-3089df44-fad9-11e7-9c51-14d369a88c8a.jpg)

**Comment by t510599** [comment]
已解決:
[https://github.com/stoneapptech/webeditor/commit/df3edf5363f526ec459b3112a3d30d7766952274](https://github.com/stoneapptech/webeditor/commit/df3edf5363f526ec459b3112a3d30d7766952274)

**Comment by YamiOdymel** [comment]
啊⋯⋯這個確實是已知問題，會在 2.4 有完整的修正。
