### ISSUE TITLE
Title is not white in .ts.slate with image

### ISSUE THREAD

**Issue by toby3d** [teacat/tocas#581]
**Example:**
```html
<header class="ts massive basic borderless extra vertically padded slate">
  <div class="image">
    <img class="tablet or large device only" src="/header.jpg" alt="header">
  </div>
  <span class="header">Lorem ipsum</span>
  <span class="description">Lorem ipsum dolor sit amet, consectetur adipisicing elit.</span>
</header>
```

**Result:** Black header text with white description text.

**Comment by YamiOdymel** [comment]
I don't see any problem?

![2018-01-26 11 06 55](https://user-images.githubusercontent.com/7308718/35445775-a2d1a85e-02ed-11e8-8264-df7bef383f2c.png)

**Comment by toby3d** [comment]
Strange, because I use latest dist from repo and get this:
![default](https://user-images.githubusercontent.com/5412322/35465439-cf155e80-031d-11e8-9147-41e89b79fe76.png)
(have image as background)

I fix that by this style rule:
```css
.ts.slate .image:not(i) ~ .header {
    color: #ffffff !important;
}
```
