### ISSUE TITLE
Sidebar 能在不同裝置下有不同常駐、顯示方法

### ISSUE THREAD

**Issue by itshenrywu** [teacat/tocas#586]
電腦板變常駐 + 擠壓
手機版變隱藏 + 覆蓋

使用同一個元素達成

---

https://github.com/itamarst/semantic-sidebar-example
https://itamarst.github.io/semantic-sidebar-example/

**Comment by YamiOdymel** [comment]
這個方法應該會透過 JavaScript 完成。

主要在 `sidebar` 上加上 `responsively visible` 作為判斷依據。

然後在行動裝置上透過 JavaScript 先將 `visible` 移除避免顯示，接著在 `sidebar` 上加上 `overlapped` 來允許層疊。

在電腦裝置則自動在 `pusher` 上加上 `squeezable` 來允許 Pusher 被擠壓。

**Comment by YamiOdymel** [comment]
更改為幾乎設置都能在 JavaScript 中配置，而不需要指定 Class。所以也不用加上 `responsively visible`、`squeezable pusher`，基本上就是在初始化 Sidebar 時像這樣使用。

```javascript
ts('.sidebar').sidebar// 消音所有提示，甚至是錯誤訊息。
({
  // 是否要在側邊欄出現的時候淡化頁面。
  dimPage: true,
  // 是否允許使用者點擊頁面關閉側邊欄。
  closable: true,
  // 是否要在側邊欄出現的時候所動頁面捲軸滾動。
  scrollLock: false,
  // 側邊欄的出場效果。（`overlay` 為覆蓋、`push` 為推出、`squeeze` 為擠壓）
  transition: 'overlay',
  // 預設的顯示模式，設為 `auto` 的時候出場效果會被覆蓋。（`auto` 為電腦常駐、行動裝置隱藏、`static` 為常駐、`hidden` 為預設隱藏）
  visibility: 'hidden',
  // 當側邊欄剛出現時所會呼叫的回呼函式。
  onVisible: () => {},
  // 當側邊欄出現動畫結束時所會呼叫的回呼函式。
  onShow: () => {},
  // 當側邊欄可見狀態有所變更且動畫執行完畢時所會呼叫的回呼函式。
  onChange: () => {},
  // 當側邊欄關閉時所會呼叫的回呼函式。
  onHide: () => {},
  // 當側邊欄關閉動畫結束時所會呼叫的回呼函式。
  onHidden: () => {}
});
```
