### ISSUE TITLE
[Enhancement request] Docs 圖示頁面優化

### ISSUE THREAD

**Issue by racterub** [teacat/tocas#589]
[Tocas-UI 圖示](https://tocas-ui.com/element/icon)
讀了一段時間還沒讀完

或許用類別分類，各建一個下拉頁，點選下拉頁的時候再去加載圖示？？

**Comment by itshenrywu** [comment]
這個會跟 3.0 板文件一起處理

**Comment by YamiOdymel** [comment]
這個問題會跟 #560 一同修正。

讀取時間問題會在 Tocas 3.0 改為靜態 HTML 文件解決。

另一個問題是：「每個圖示都有一個 Event Listener，導致網頁卡頓。」

也會一起修正。
