### ISSUE TITLE
可捲動、滑動式 Table

### ISSUE THREAD

**Issue by racterub** [teacat/tocas#591]
### 讓 table 在手機上能夠自動調整成可滑動
(Tocas-Ui 在使用 table 時，如果 table 尺寸大於 container，則 table 會直接超出 container
電腦視角：
![電腦視角](https://i.imgur.com/5iq2DuW.png)
手機視角
![手機視角](https://i.imgur.com/bD3aYWU.png)

Example -> `Bootstrap4 .table-responsive`

**Comment by YamiOdymel** [comment]
跟這個功能⋯⋯應該類似或相同。

[[T2] 新增吸附式 Table 標頭（Table Data-Grid）](https://github.com/TeaMeow/TocasUI/issues/333)

**Comment by racterub** [comment]
@YamiOdymel  對，我剛剛有看到，原本要刪掉..

**Comment by YamiOdymel** [comment]
不過說實話，CSS 殘廢到不能固定上面的 Header，所以我還在想該怎麼處理。

搞不好要把 Table 的內容複製然後建立幾個 Div 去做特殊處理什麼的⋯⋯。

**Comment by racterub** [comment]
@YamiOdymel 有 Example 不過他是用 jQuery...
[Example](http://www.gbtags.com/gb/demoviewer/2712/799f88d4-1dca-4ffc-9d45-434e2598d31d/index.html.htm)
http://blog.csdn.net/q3585914/article/details/69946086

**Comment by YamiOdymel** [comment]
我想上吊。

**Comment by YamiOdymel** [comment]
仔細看了一下，跟 Data-Grid 貌似又有點不同的是⋯⋯Bootstrap 的版本很簡單地只在 `<table>` 外側加上了一個 Wrapper。

如果把 Table 放在一個可以捲動的 Segment 裏，這個問題好像能解決。

**Comment by racterub** [comment]
我發現我把我自己的成績po上去了幹

**Comment by YamiOdymel** [comment]
合併到 #604
