### ISSUE TITLE
將網格系統的響應式寬度自動向上相容

### ISSUE THREAD

**Issue by goodjack** [teacat/tocas#606]
不曉得我是不是用錯方法
有沒有方法可以從 `tablet` 以上指定一種寬度呢？

也有試過改成 `tablet or large device`
好像行不通

下方是指定 `tablet` 和 `computer` 的比較
遊樂場：https://goo.gl/RbyzPM

![image](https://user-images.githubusercontent.com/1116129/37241623-0f7da55a-2497-11e8-89ca-5f2613663a2f.png)

```html
<div class="ts grid">
    <div class="four wide tablet eight wide mobile column"><div class="ts inverted primary segment"></div></div>
    <div class="four wide tablet eight wide mobile column"><div class="ts inverted primary segment"></div></div>
    <div class="four wide tablet eight wide mobile column"><div class="ts inverted primary segment"></div></div>
    <div class="four wide tablet eight wide mobile column"><div class="ts inverted primary segment"></div></div>
    
    <div class="four wide computer eight wide mobile column"><div class="ts inverted positive segment"></div></div>
    <div class="four wide computer eight wide mobile column"><div class="ts inverted positive segment"></div></div>
    <div class="four wide computer eight wide mobile column"><div class="ts inverted positive segment"></div></div>
    <div class="four wide computer eight wide mobile column"><div class="ts inverted positive segment"></div></div>
</div>
```

**Comment by goodjack** [comment]
目前找到的解法是
```html
<div class="four wide computer four wide tablet eight wide mobile column">
```

**Comment by YamiOdymel** [comment]
簡單說就是：應該要追加一個 `mobile` 以上，給 `tablet` 和 `computer` 共享的 `wide` 欄位寬度嗎。

當初確實有想到這一點，不過看到 Semantic UI 沒什麼人抱怨，

所以就乾脆直接寫成 `four wide computer four wide tablet` 了。

**Comment by YamiOdymel** [comment]
`four wide tablet or large device` 感覺也有點夭壽長跟混淆，看來需要一個好名稱⋯⋯。

**Comment by YamiOdymel** [comment]
我問問，預期的效果應該是像下面這樣嗎？

![2018-03-26 7 09 18](https://user-images.githubusercontent.com/7308718/37903083-41c8f962-3129-11e8-986c-ffacbd2b242f.png)

現在新的做法是會向上相容。

例如： `four wide tablet two wide mobile`

* 在電腦上觀看會是 `four wide`
* 平板也是 `four wide`
* 行動裝置則是 `two wide`

**Comment by goodjack** [comment]
現在才看到 抱歉 😅
是這個想法沒錯

這同時也解決了原本大型螢幕需要額外指定的問題
感謝 🙏
