### ISSUE TITLE
與 chart.js 配合時卡片功能異常

### ISSUE THREAD

**Issue by goodjack** [teacat/tocas#611]
目前測試只有我電腦上的 Chrome Beta 異常
版本 66.0.3359.45 (正式版本) beta (64 位元) / macOS 10.12.6
我手邊沒有正式版的 Chrome

Firefox 59.0.1 (64 位元) 和 Safari 11.0.2（12604.4.7.1.6）是正常的
Android 上的 Chrome 也是正常

原始碼：https://jsfiddle.net/goodjack/t9c6htby/2/

----

![image](https://user-images.githubusercontent.com/1116129/37843718-b8de30ce-2f00-11e8-90c3-70caf6268fca.png)

上面那個截圖中
只有最左邊直的兩個會有懸浮效果和超連結

其他的都是像靜態圖片一樣
沒有超連結功能、沒有手指游標、也沒有懸浮效果
如果 waterfall 的 card 再給多一點，也是只有最左邊那一排才會正常

視窗寬度調成手機寬度的話
也是只有左邊那排有正常效果和功能

----

用右鍵檢查看 `<a>` tag 是正常的
Console 裡也沒有錯誤
![image](https://user-images.githubusercontent.com/1116129/37843860-0a63af14-2f01-11e8-8187-cd69643041b5.png)

----

以下狀況會恢復正常：
1. 把 script 的東西註解掉...
2. 調整圖表 card 的 wide 有時候可以，我目前找不到規律

不知道有沒有理解我的敘述（汗

**Comment by YamiOdymel** [comment]
看起來這個問題只有在 Chrome Beta 上發生，目前正式版沒問題。主要問題應該是 `.ts.cards` 的負外距造成的問題，取消就沒事了（詳細一點：當垂直外距大於（更負） `-12px` 的時候貌似就會出事）。

但是這個樣式是必要的（因為每張卡片都有外距，所以需要在卡片群組「抵銷」他們的外距），有時候 Beta 的問題不一定會在正式上出現就是了⋯⋯但有些 Bug 會保留，最近來看看。

![2018-03-24 2 29 35](https://user-images.githubusercontent.com/7308718/37847291-4c3d9df0-2f0b-11e8-8b30-99311a0790aa.png)

**Comment by YamiOdymel** [comment]
然後現在正式版的 Chrome 遇上這個問題了，Chromium 你在衝蝦毀

**Comment by YamiOdymel** [comment]
好吧，不曉得是誰的錯。Chart.js 的 Canvas 的 `z-index` 設置為 `1` 就能解決這個問題了。

但是看了一下 Canvas 並沒有遮蓋住整個畫面⋯⋯真是奇異。
