### ISSUE TITLE
對話在 chrome 顯示異常

### ISSUE THREAD

**Issue by t510599** [teacat/tocas#628]
左邊是 chrome , 右邊是 firefox
![default](https://user-images.githubusercontent.com/18533304/38492119-8f8b643a-3c20-11e8-9ac9-fbd12723a03d.png)

**Comment by itshenrywu** [comment]
我也有遇到同樣的情況

**Comment by coin3x** [comment]
跟 #531 同個問題
029b8a2c 已經修正這個問題了
要等 3.0 出來才會解決ㄅ

**Comment by t510599** [comment]
抱歉 沒看到
