### ISSUE TITLE
[建議] 繼續閱讀的功能

### ISSUE THREAD

**Issue by goodjack** [teacat/tocas#642]
[範例來自 Google Play](https://play.google.com/store/apps/details?id=com.facebook.katana&hl=zh-tw)
文字太多的時候只預覽前面的部分，點選繼續閱讀展開

![image](https://user-images.githubusercontent.com/1116129/39469417-b065c154-4d6a-11e8-893e-c62458058308.png)

**Comment by YamiOdymel** [comment]
雖然說 Tocas 現在已經有了 Accordion（手風琴；能夠開關閉合的元件），不過那東西用純展開更多文字內容上可能有點小小不適合（_也有可能會合併 🤔？_）。

因為 Google Play 的元素名稱有被擾亂所以特地跑到 YouTube 看了一下類似的東西（他們稱之為 
 Expander）。

![2018-05-02 3 50 40](https://user-images.githubusercontent.com/7308718/39512417-823e85cc-4e23-11e8-8b7d-2fbd3af90a03.png)

而[這個 Codepen](https://codepen.io/joserick/pen/ooVPwR) 則是稱其為 `Collapse`（開、閉合；BootStrap 的用法），其實這種簡潔的外觀⋯⋯貌似還不錯。

![2018-05-02 4 12 40](https://user-images.githubusercontent.com/7308718/39512464-adc86262-4e23-11e8-9795-310685d45801.png)

![2018-05-02 4 12 43](https://user-images.githubusercontent.com/7308718/39512468-b3a12c46-4e23-11e8-931f-6a1da6662e42.png)

就目前來看，會以 Expander 作為主要的命名方式。不過 HTML 結構跟相關的樣式名稱倒是有點讓我想不出來。

畢竟有的人希望像 YouTube 那樣直接裁切文字、或 Google Play 那樣用漸層蓋著文字（甚至上面範例那樣以「行數」裁切）。

```html
<!-- 展開者 -->
<div class="ts expander">
    <div class="content">
        <!-- ... -->
    </div>
</div>
<!-- / 展開者 -->
```

大略的 JavaScript 用法可能如下（順帶參考一下 [Readmore.js](https://github.com/jedfoster/Readmore.js)）。

```js
ts('.expander').expander({
    // 預覽文字行數，如果內容短於此行數則不會顯示展開按鈕。
    previewLines: 3,
    // 文字狀態。
    // （如果有指定此選項則採用預設的按鈕？）
    text: {
        inactive: '更多資訊',
        active  : '收起資訊'
    },
    // 控制按鈕。
    // （由使用者自行建立的按鈕，如果有此選項則忽略文字狀態選項且不要產生預設按鈕？）
    toggle: {
        expand  : '.expand.button',
        collapse: '.collapse.button',
    }
    // 其他鳥狀態監聽器。
    onExpanding : () => {},
    onExpand    : () => {},
    onCollapsing: () => {},
    onCollapse  : () => {},
    onChange    : () => {},
})

// 其它用法。
ts('.expander').expander('is expanded')
ts('.expander').expander('is collapsed')
ts('.expander').expander('expand')
ts('.expander').expander('collapse')
```
