### ISSUE TITLE
新增 Colored Text 帶文字的 `ts text`？

### ISSUE THREAD

**Issue by YamiOdymel** [teacat/tocas#643]
![2018-05-01 6 19 57](https://user-images.githubusercontent.com/7308718/39470488-a434387e-4d70-11e8-8caf-0e6f9480d31f.png)

同時帶有 `.ts.secondary.text` 來淡化文字，而不是什麼 `.ts.faded.message`。

其它用法像是 `.ts.positive.text`、`.ts.primary.text`。

https://github.com/Semantic-Org/Semantic-UI/issues/1885
https://github.com/Semantic-Org/Semantic-UI/issues/2654

**Comment by lubber-de** [comment]
Implemented in Fomantic UI 2.7
https://fomantic-ui.com/elements/text.html
