### ISSUE TITLE
Icons（多個圖示）顯示不正確

### ISSUE THREAD

**Issue by goodjack** [teacat/tocas#644]
用 Chrome 和 Firefox 看都是偏右
另外 Chrome 的左側還會裁切到一點

## Chrome
![image](https://user-images.githubusercontent.com/1116129/39470675-893f512e-4d71-11e8-91bf-6d7db47f9df5.png)

## Firefox
![image](https://user-images.githubusercontent.com/1116129/39470688-953397ec-4d71-11e8-9e43-fb54fa88aa5d.png)

---
[遊樂場連結](https://tocas-ui.com/try/?html=%3Ci%20class=%22large%20icons%22%3E%5Cn%20%20%20%20%3Ci%20class=%22big%20thin%20circle%20icon%22%3E%3C/i%3E%5Cn%20%20%20%20%3Ci%20class=%22user%20icon%22%3E%3C/i%3E%5Cn%3C/i%3E%5Cn%5Cn%20%3Ci%20class=%22large%20icons%22%3E%5Cn%20%20%20%20%3Ci%20class=%22big%20circle%20icon%22%3E%3C/i%3E%5Cn%20%20%20%20%3Ci%20class=%22inverted%20bell%20icon%22%3E%3C/i%3E%5Cn%3C/i%3E)

```html
<i class="large icons">
    <i class="big thin circle icon"></i>
    <i class="user icon"></i>
</i>

 <i class="large icons">
    <i class="big circle icon"></i>
    <i class="inverted bell icon"></i>
</i>
```

**Comment by YamiOdymel** [comment]
看起來是 `i.icons .icon:first-child` 裡有個 `margin-right` 所導致。
