### ISSUE TITLE
移除所有元件的預設陰影

### ISSUE THREAD

**Issue by YamiOdymel** [teacat/tocas#654]
基本上有一半已成定局，有一半是繼續保留，繼續思考中。

不過陰影確實有點小小的沈重感，Material 和 DailyMotion 那樣反倒還感覺更亮麗、大氣。

**Comment by gnehs** [comment]
我都直接把陰影弄多一點，然後框線弄掉

**Comment by YamiOdymel** [comment]
14 天過去了，這個建議依然沒有 Vote Down 的跡象。
