### ISSUE TITLE
表格邊框不正常

### ISSUE THREAD

**Issue by gnehs** [teacat/tocas#655]
https://bit.ly/2shCpyP

Tocas 3.0 Alpha 1 一樣有此問題

**Comment by YamiOdymel** [comment]
雖然不夠直覺，但基本上應該在較複雜的結構表格中加上 `structured`（結構的） 樣式，這樣就能修復這個問題。

這個樣式主要會加上 `border-collapse: collapse;` 樣式來合併框線，

缺點是表格的四邊圓角會消失變成直角，這也是為什麼 Table 預設沒有這個樣式。

---

相近問題：
https://github.com/Semantic-Org/Semantic-UI/issues/1359
https://github.com/Semantic-Org/Semantic-UI/issues/1293
https://github.com/Semantic-Org/Semantic-UI/issues/5395
