### ISSUE TITLE
更改 README 佈局

### ISSUE THREAD

**Issue by YamiOdymel** [teacat/tocas#667]
為什麼我們的 README 不能像這個一樣好呢？喔，就快了。

![2018-07-01 3 40 49](https://user-images.githubusercontent.com/7308718/42128540-9aae597a-7ce0-11e8-83d9-c2b27fe3e74b.png)

https://github.com/alibaba/ice

**Comment by coin3x** [comment]
![default](https://user-images.githubusercontent.com/9127594/42223097-854bc5ec-7f09-11e8-99e1-0920ce86a570.png)
可是如果你要讓圖片浮在右邊 你就會用到棄用的元素屬性(?
標題置中也是
好像沒辦法用 style="" 的樣子
