### ISSUE TITLE
Form 要支援 Multiple Select

### ISSUE THREAD

**Issue by YamiOdymel** [teacat/tocas#672]
![photo_2018-07-06_04-31-15](https://user-images.githubusercontent.com/7308718/42346495-6f13d4ae-80d5-11e8-8625-44a036be5ace.jpg)

```html
<div class="field">
  <label>Tags</label>
  <select v-model="post.tags" multiple>
    <option v-for="tag in tags" v-bind:value.number="tag.id">
      <template v-if="tag.category != ''">${tag.category}:</template>${tag.tag}
    </option>
  </select>
</div>
```

然而正常用法需要透過 

```
<select class="ts basic dropdown" v-model="post.tags" multiple size="3">
```

**Comment by coin3x** [comment]
不懂現在缺了什麼功能 是要讓它能夠在 class 寫 multiple 就好了嗎

**Comment by YamiOdymel** [comment]
剛才沒什麼時間寫完整一點，主要是在 Form 裡面的 Select 通常會自動被套上 `.ts.basic.dropdown` 的樣式來避免寫得很複雜。

但是 Form 裡面的 Select[Multiple] 會被當成普通的 Select 看待，並且套用下拉式選單的箭頭圖示。

所以這次該更改的主要是讓 Form 裡面的 Select[Multiple] 樣式能夠變得跟 `.ts.basic.dropdown[multiple]` 一樣。

![2018-07-06 4 56 51](https://user-images.githubusercontent.com/7308718/42347626-04dc1e58-80d9-11e8-8d02-3b4bb8134bf9.png)
