### ISSUE TITLE
ts.menu .menu 是否可設定為啟用狀態

### ISSUE THREAD

**Issue by racterub** [teacat/tocas#679]
在使用側邊欄時發現的問題，看 Docs 也沒有提到
圖片:
![2018-07-20 9 52 56](https://user-images.githubusercontent.com/20561837/43006056-4d77512a-8c67-11e8-8315-158e1294ed73.png)
Chrome Dev tool:
![2018-07-20 9 53 39](https://user-images.githubusercontent.com/20561837/43006088-62ced87c-8c67-11e8-8316-f23df02e8356.png)

Code:
[https://gist.github.com/racterub/60012bba6449f5c71281b0b88bc1cca1](https://gist.github.com/racterub/60012bba6449f5c71281b0b88bc1cca1)

**Comment by YamiOdymel** [comment]
看起來項目有啟用，不過顏色比較淡⋯？

**Comment by racterub** [comment]
@YamiOdymel 剛剛用原始的 menu 測了一下，發現是字加粗了..
![image](https://user-images.githubusercontent.com/20561837/43006639-ce4db8d8-8c68-11e8-9f94-51fd6a81c7b9.png)

**Comment by racterub** [comment]
剛剛在 Docs 找到敘述了，或許在 inverted 的時候選擇背景加深？

**Comment by YamiOdymel** [comment]
看起來只能搞得跟 Header 一樣亮了嗎

![2018-07-20 9 46 19](https://user-images.githubusercontent.com/7308718/43008555-fda2d8b6-8c6d-11e8-815d-874526280719.png)
