### ISSUE TITLE
font-family 考虑不同地区的字形标准

### ISSUE THREAD

**Issue by haiwx** [teacat/tocas#681]
如题。

**Comment by YamiOdymel** [comment]
目前的字型標準是：

```
"SF Pro TC","SF Pro Text","SF Pro Icons","PingFang TC","Helvetica Neue","Helvetica","Arial",
"Microsoft JhengHei",wf_SegoeUI,"Segoe UI",Segoe,"Segoe WP",Tahoma,Verdana,
Ubuntu,"Bitstream Vera Sans","DejaVu Sans",Tahoma,微軟正黑體,"LiHei Pro",
"WenQuanYi Micro Hei","Droid Sans Fallback","AR PL UMing TW",Roboto,
"Helvetica Neue","Hiragino Maru Gothic ProN",メイリオ,"ヒラギノ丸ゴ ProN W4",
Meiryo,"Droid Sans",sans-serif
```

當初追加的規則是從 Ubuntu 和一些 Windows 系統上面抄來的，不太清楚簡體字系都用哪些 Font（而且這些 Font 要盡量是簡體語系裝置內建的）。

**Comment by haiwx** [comment]
@YamiOdymel Windows 上简体中文默认字体是“微软雅黑”（Microsoft YaHei），MacOS 是 Pingfang SC。比较麻烦的是一套 font-family 可能无法实现这一点，比如 Win 简中系统上同样有“微软正黑”字体。我能想到的解决方案是，多套 font-family，亦或是不用罗列那么多，直接“arial, sans-serif;”回退默认浏览器默认无衬线字体。

**Comment by YamiOdymel** [comment]
我不太能理解「一套 `font-family` 可能無法實現」是什麼意思，因為如果裡面安插了簡體的字型，應該就能在簡體系統上正確套用，繁體系統會因為沒有該字體而無法套用所以退回到其他繁體字型吧？

意思是：可能簡體系統上有繁體字型，然後會被套用到導致缺字之類的問題？

我是不太知道該怎麼讓 `font-family` 去對應瀏覽器語系來做變更啦…。也許是在 `<html>` 標籤裡面設置 `lang="zh-CN"` 然後以 `*:lang(zh-CN)` CSS 選擇器來更改主要的 `font-family` 嗎 🤔

**Comment by haiwx** [comment]
@YamiOdymel Okay，测试可行。下面给出一个简中的常见配置仅供您参考。

```
*:lang(zh_CN){
  font-family: "Helvetica Neue", Helvetica, Arial, "PingFang SC", "Hiragino Sans GB", "Heiti SC", "Microsoft YaHei", "WenQuanYi Micro Hei", sans-serif;
}
```
