### ISSUE TITLE
ts fluid action input 顯示異常

### ISSUE THREAD

**Issue by t510599** [teacat/tocas#685]
顯示寬度會超出元素的寬度
![tocas fluid button](https://user-images.githubusercontent.com/18533304/43590101-d53a2d7c-96a2-11e8-9132-7669b4dde991.png)

**Comment by YamiOdymel** [comment]
這個問題我在 Tocas 3.0 開發的時候試不出來，先推測是被修正過了。

![image](https://user-images.githubusercontent.com/7308718/48830664-18bf0900-edb0-11e8-9ce4-d9b1dba4ec36.png)

```pug
.ts.segment(style="width: 200px")
    .ts.fluid.action.input
        input(type="text" placeholder="在這裡搜尋人事物")
        button.ts.button 搜尋
```
