### ISSUE TITLE
如果要加入iframe , tag要使用什麼UI元素呢? , ts container 放入iframe, 顯示不出來XD

### ISSUE THREAD

**Issue by cn27529** [teacat/tocas#687]
如果要加入iframe , tag要使用什麼UI元素呢? , ts container 放入iframe, 顯示不出來XD

**Comment by YamiOdymel** [comment]
不太清楚你的意思，要使用 iframe 的話基本上用在任何地方都是沒問題的喔？

會不會是瀏覽器的安全設置之類的擋掉了 iframe 的內容呢？

**Comment by cn27529** [comment]
哈哈 後來我用pdfobject js解了，因為直接用div都不行捏XDDD，感謝你

**Comment by YamiOdymel** [comment]
聽起來是很奇異的事情，要是哪天又發生而且沒辦法解決的話就再提出來討論看看吧

**Comment by cn27529** [comment]
謝謝，好哦
