### ISSUE TITLE
Docs 網站 範例下載連結錯誤

### ISSUE THREAD

**Issue by racterub** [teacat/tocas#693]
好像誤植ㄌ
![image](https://user-images.githubusercontent.com/20561837/45375646-2cb7f300-b628-11e8-9de7-fb947178fb09.png)

**Comment by racterub** [comment]
https://github.com/TeaMeow/TocasUI/examples ??

**Comment by racterub** [comment]
https://github.com/TeaMeow/TocasUI/tree/master/examples ??

**Comment by YamiOdymel** [comment]
好像過了很久才回，這個連結沒有誤植，當初有刻意要把 TocasUI 獨立成一個 Org 組織處理，不過最近 3.0 應該會考慮全部集中在 `teacat/tocas` 中。
