### ISSUE TITLE
sortable功能跳出錯誤

### ISSUE THREAD

**Issue by city8208** [teacat/tocas#700]
<img src="https://i.imgur.com/a7SLH9W.gif" alt="image" style="max-width:100%;">

這次與之前狀況可能是同一個問題(表格內放不是純文字，有input/select 那些元件)
當我透過onmouseover 去啟用ts('.ts.sortable.table').tablesort();時

會跳出這個錯誤
Uncaught TypeError: Cannot read property 'each' of null
    at HTMLTableElement.<anonymous> (tocas.js:36)
    at tocas.js:9
    at Array.every (<anonymous>)
    at Array.each (tocas.js:9)
    at Array.ts.fn.tablesort (tocas.js:35)
    at Newdragontablesort (TableWorkType1.js:24)
    at HTMLTableElement.onmouseover (EditPage.php:9)

**Comment by city8208** [comment]
備註：奇怪的是   
我直接呼叫Table id  
ts('#tableName').tablesort();
卻沒有出現這個錯誤，由於該頁面裡有複數以上的表，不知道是不是多個表呼叫造成的錯誤
提供給您做參考

**Comment by city8208** [comment]
<img src="https://i.imgur.com/gcwiEil.png" alt="image" style="max-width:100%;">

不好意思，這個是新的問題，
當我為了設定Table的 overflow: auto;，而將display 改為block後 (display: block;)，
表單縮小了(正常)，但是縮小的表單右邊及下方的框線不見了。

**Comment by YamiOdymel** [comment]
Table 本身只能是 `display: table`，這樣才能用上表格的一些屬性，所以沒辦法改成 `block`

**Comment by city8208** [comment]
那這樣的狀況下，假如我要使用 overflow屬性，應該要怎麼做
(直接設定是無效的，display table 會強制縮排或跳行，但實際表格編輯都是跳出卷軸)

**Comment by YamiOdymel** [comment]
Overflow 其實在 Table 上有點小障礙，像是 Bootstrap 的用法是透過一個 Div 把 Table 包起來，然後讓那個 Div 有著 Overflow，最糟糕的狀況可能就是需要搭配 JavaScript。

下一個版本 Tocas 3.0 的新版本有打算解決 Table Overflow 的問題，但目前 2.3.3 還沒辦法做出太大的修改。

**Comment by city8208** [comment]
是的，目前我也是這樣
(DIV包起來後，讓表頭變成浮動的)

不過還是期待您的更新
