### ISSUE TITLE
響應式中 large 之裝置與元素尺寸命名衝突

### ISSUE THREAD

**Issue by t510599** [teacat/tocas#711]
Ex:
```html
<button class="ts large device only button">Click</button>
```

這樣會呈現一個 `.ts.large.button`

**Comment by YamiOdymel** [comment]
這個是我很頭痛的問題，基本上要不是 Tocas UI 命名全部改成 `ts -large-device-only button` 就是將響應式用法改成 `<button data-rwd="large device only">`。

前者是比較有可能的作法，因為我有意將整個 Tocas UI 的用法改成減號前輟，後者的作法倒是也有可能，但這樣可能讓使用者沒辦法認清什麼時候該用元素的 Attribute 指定，什麼時候該用 Class 指定。

如果改用 Attribute，那麼 Grid 網格系統的寬度細分是不是也該改成 `data-wide="3"` 這樣的用法而不是 `three wide column`？

一堆問題隨之而來，現在還沒想到什麼太好的方法。

目前能做的暫時用法就是用另一個 `.large.device.only` 的 Div 把按鈕包住，但是這在某些依賴 `a > b` 這種相近元素下，反倒會導致部份的樣式失效就是了…（例如說：`.ts.buttons > .ts.button` 這個時候就沒辦法用上一個 Div 包住 Button，否則 CSS 選擇器會失效）。
