### ISSUE TITLE
手機板介面 下方功能列無法切換選擇

### ISSUE THREAD

**Issue by city8208** [teacat/tocas#717]
Tocas範例的Web APP頁面
下方三個切換鈕無法在Apple手機上運行

**Comment by YamiOdymel** [comment]
因為是範例，那三個按鈕是示意作用，沒有功能。

單純展示佈局設計的用途。

**Comment by city8208** [comment]
抱歉晚回了
這部份  我是使用模塊的分頁籤

然後在使用iOS的瀏覽器以及APP內建瀏覽器(我將Web包在iOS殼內輸出成APP)
結果在Android 及PC上都能正常點擊切換
但到iOS上卻失效了(頁籤點擊後會變深色)

另外在Mac mini上  (mac osx)上 也是無法使用的
<img src="https://i.imgur.com/mQOF24q.png" alt="辛苦了洨洨安" >

**Comment by city8208** [comment]
補充：這幾天特別針對這狀況下去測，
有趣的是下方的多頁籤反而沒這狀況，只有在單頁籤且有加入點擊切換(onclick)動作時發生，
不知道是不是mac那邊會擋操作還是其他狀況

**Comment by YamiOdymel** [comment]
謝謝你詳細的說明，看起來跟 #695 和 #578 是同樣的問題…不曉得 Safari 又改了什麼，

這個問題會合併到 #578

**Comment by city8208** [comment]
不會啦  能幫到您也是小弟的福氣
後續新版肯定也會支持的

只是我現在比較不知道的是，單頁籤和多頁籤的具體差別
(至少想先把出問題這塊改成可以iOS使用)

PS：剛剛在每一個項目下新增 data-tab-group="main"後已可正常運行
