### ISSUE TITLE
暗色主題下 horizontal divider 的顏色不清楚

### ISSUE THREAD

**Issue by gnehs** [teacat/tocas#724]
`<div class="ts horizontal divider">我是分隔線</div>`
![image](https://user-images.githubusercontent.com/16719720/48976507-04d31a00-f0c4-11e8-8d37-0991f26137aa.png)

**Comment by YamiOdymel** [comment]
Horizontal Divider 是不是有 Inverted 反色語意可以使用？

**Comment by gnehs** [comment]
![image](https://user-images.githubusercontent.com/16719720/48976535-6b583800-f0c4-11e8-9d01-bd596189220e.png)
他還是同一張圖...

**Comment by YamiOdymel** [comment]
喔酷，反色語意的 Horizontal Divider 只改文字顏色和普通的分隔線顏色，左右兩邊的顏色不會改

**Comment by gnehs** [comment]
尼沒有按「哇」

**Comment by rexx0520** [comment]
哦不，甲甲閱讀器

**Comment by gnehs** [comment]
剛剛又多ㄌ幾篇喔

**Comment by rexx0520** [comment]
專法ㄅㄅㄕ：（

**Comment by gnehs** [comment]
尼也用專法結婚啦ㄍ

**Comment by rexx0520** [comment]
\(:D)/(-_-).png
