### ISSUE TITLE
側邊欄新增下拉式選單

### ISSUE THREAD

**Issue by racterub** [teacat/tocas#726]
不知道 TocasUI 3 能不能在側邊欄新增下拉式選單。
直接硬上的話會長這樣
![kapture 2018-11-26 at 0 06 33](https://user-images.githubusercontent.com/20561837/48981359-476e1400-f10f-11e8-85b8-a7c3e4c51763.gif)

**Comment by YamiOdymel** [comment]
喔不，側邊欄的用意不是讓你有功能下拉式選單的，就像 Material Design 也不鼓勵（主要是因為在行動裝置上會有螢幕尺寸擠壓問題）。

通常側邊欄是透過子選單達成目的，你在使用子選單上有什麼困擾嗎？

![image](https://user-images.githubusercontent.com/7308718/49003135-4e8f3380-f19c-11e8-866a-1e7ffea8ffdf.png)

```html
<div class="ts compact inverted vertical menu">
    <div class="item">
        <div class="header">
            成績表
        </div>
        <div class="menu">
            <a class="active item" href="#!">第一次段考</a>
            <a class="item" href="#!">第二次段考</a>
        </div>
    </div>
    <div class="item">
        <div class="header">
            帳號管理
        </div>
        <div class="menu">
            <a class="item" href="#!">個人資料</a>
            <a class="item" href="#!">安全性與密碼</a>
        </div>
    </div>
    <div class="item">
        登出
    </div>
</div>
```

**Comment by racterub** [comment]
主要是因為避免側邊欄放入過多的元素，想說不知道可不可以利用分類的方式，在不同類別中可以展開。

**Comment by racterub** [comment]
e.g. https://bootsnipp.com/snippets/featured/side-menu-on-hover
但是畢竟這只是一個新功能，如果螢幕尺寸擠壓問題，我覺得 Issue 可以保留，若之後需要的話可以在開起來討論 (?

**Comment by YamiOdymel** [comment]
如果你指的是像手風琴那樣的 Accordion 展開的話…我其實有在做，至於 Dropdown 的下拉式我沒有考慮過就是了。

**Comment by racterub** [comment]
....... 我一開始搞錯了... 這會跟3.0一起出？

**Comment by YamiOdymel** [comment]
如果你說的是可以向下展開的子選單，會包含在 Tocas 3.0 裡。

我原本以為你主張的是要求追加有下拉式選單（Dropdown）的側邊欄選單（像下圖這樣）。

![image](https://user-images.githubusercontent.com/7308718/49013763-c4a19380-f1b8-11e8-9176-3329896f49e4.png)

**Comment by YamiOdymel** [comment]
![image](https://user-images.githubusercontent.com/7308718/49419828-9a0c9780-f7c3-11e8-89c7-079d12333248.png)

稍微標記一下，這個提議同時也出現在 Semantic UI 社群分歧的 Formatic UI 中。

https://github.com/fomantic/Fomantic-UI/issues/258

而且有線上 Demo 可以展示：https://jsfiddle.net/adf13s6b/
