### ISSUE TITLE
能夠存放社群大眾 Tocas UI 片段 / 主題的：網路「商店」

### ISSUE THREAD

**Issue by YamiOdymel** [teacat/tocas#730]
先替之後 2019 年的 Tocas UI 3.x 著想。

由於元件跟著變多，相對的使用方法也會多到爆炸。這意味著會有很多不同的元件搭配形式可以使用，為此需要生出一個能夠存放、讓大家編輯 Tocas UI 程式碼的地方：網路商店（Web Store）。

雖然說是商店，不過當然所有東西都是免費的，所以這也不能叫做商店（Store），不如說像是 GitHub Gist 的地方（舉例：[BootSnipp](https://bootsnipp.com)），但是功能跟分類上可能又好一點，所以需要替這個網站額外想一個名字。

這個網站的架構不外乎會是 Golang + MySQL（或是 SQLite？），也有可能和 Vue.js 搭配。

![image](https://user-images.githubusercontent.com/7308718/50404708-e9a01b00-07e5-11e9-9daa-6b4bd03eb078.png)

**Comment by gnehs** [comment]
我只看到延期

**Comment by hugwalk** [comment]
🤔 Tocas Market
Tocas Library
Tocas Hub (?)

**Comment by goodjack** [comment]
TocasHub +1 👍👍

**Comment by Asteriska001** [comment]
TocasBar 😄

**Comment by t510599** [comment]
Tocas Base
