### ISSUE TITLE
字型設定寫在 body 裡

### ISSUE THREAD

**Issue by junyussh** [teacat/tocas#733]
可不可以把網頁的字體設定寫在 `body` 標籤裡，如果寫在 `*` 中，會全局覆蓋字型，假如我想要在某個區塊內改變字型，就會被 `*` 的設定蓋過，唯一的方式是覆寫 `*` 中的 `font-family`，但這樣又會造成所有區塊都變成我設定的字型。

**Comment by YamiOdymel** [comment]
`*` 的優先度是非常低下的，當初我記得是放在 `html` 裡面，但是有些元素會沒有繼承到這些 `font-family` 而導致比較深層的子元素沒有套用到 Tocas 偏好的 `font-family`。

總覺得有點兩難，或者應該在 `html` 或 `body` 中追加一個 `[data-default-font]` 來讓 Tocas 使用預設的字型，不要特別去設置 `font-family`

**Comment by junyussh** [comment]
那我如果想要在區塊內使用特定字體，我該怎麼寫比較好？
