### ISSUE TITLE
新增 PIN 碼 Input

### ISSUE THREAD

**Issue by YamiOdymel** [teacat/tocas#738]
![image](https://user-images.githubusercontent.com/7308718/52367872-0c317f00-2a88-11e9-8f60-525f5d455d2a.png)

從 vk.com ㄎㄧㄤ下來的，基本上大概就是這樣。

```html
<div class="ts pin input">
    <input type="text">
    <input type="text">
    <input type="text">
    <input type="text">
</div>
```

或者是可以指定 `four pin input` 與 `eight pin input` 來自動該改 Input 輸入欄位的字體大小。

**Comment by gnehs** [comment]
他是不是還要自動幫你按 tab
