### ISSUE TITLE
menu 和 container 合用時出現異常

### ISSUE THREAD

**Issue by racterub** [teacat/tocas#739]
網頁的原始碼放在 GitHub 上面ㄌ (https://github.com/racterub/tyshscore-web/blob/dev/website/templates/index.jinja.html)

想問的是我在電腦上面瀏覽時 container 無視 menu 直接往上蓋，導致 menu 把 container 的內容蓋掉
![image](https://user-images.githubusercontent.com/20561837/52565050-b15da600-2e40-11e9-82cd-7c6dad277620.png)

![image](https://user-images.githubusercontent.com/20561837/52565043-ac005b80-2e40-11e9-9c26-82451b183740.png)

不太確定是不是我把 container 包在 pusher 裡面這個做法不對QQ

**Comment by racterub** [comment]
預期類似長這樣
![image](https://user-images.githubusercontent.com/20561837/52565118-e10cae00-2e40-11e9-9145-b51621f340b1.png)

**Comment by racterub** [comment]
預期是類似長這樣
![image](https://user-images.githubusercontent.com/20561837/52565147-f84b9b80-2e40-11e9-9d43-de27faa13de8.png)

**Comment by YamiOdymel** [comment]
我覺得你的 Menu 可能是浮動元素，所以高度不被計算？要看一下 Menu 的 `position` 是什麼

**Comment by racterub** [comment]
![image](https://user-images.githubusercontent.com/20561837/52565328-7740d400-2e41-11e9-8cc5-7489468092fb.png)
應該是這個(?

**Comment by racterub** [comment]
class 把 `top fixed` 拔掉就沒什麼問題了，但是感覺間隔還是好小
![image](https://user-images.githubusercontent.com/20561837/52565519-00580b00-2e42-11e9-9851-a5679bd4ab07.png)

**Comment by YamiOdymel** [comment]
`position: fixed` 基本上就是讓 Menu 固定在螢幕畫面上，但同時也會讓他變成浮動元素所以就會從原本的「網頁」中被剝離而無法計算其高度。

所以我覺得 `top fixed` 跟其他 `bottom fixed` 之類的用法都很有爭議，因為會發生這個問題。

至於 Menu 跟 Container 之間沒有間隙主要是因為有時候會跟其他想要緊鄰的元素搭配，如果自動追加 Margin 反倒會有不預期的效果，透過 Divider 分隔線多少可以增加一點間距。

```html
<div class="ts menu"></div>
<div class="ts hidden divider"></div>
<div class="ts container"></div>
```

**Comment by racterub** [comment]
hmmm，目前我還是先把 top fixed 拔掉好了
我不太熟前端，這個 issue 還是留著讓其他人一起討論好了。
