### ISSUE TITLE
[建議] 小型卡片

### ISSUE THREAD

**Issue by goodjack** [teacat/tocas#742]
類似左邊這種 Twitter Card 的效果

![](https://warfareplugins.com/wp-content/uploads/two-types-of-twitter-cards-1920x1080.jpg)

**Comment by YamiOdymel** [comment]
仔細想想這好像是使用者該自己處理的事情，難道我要用 JavaScript 自動縮減內容來讓 Card 可以延展嗎 🤔 

不過這樣的元素我上次在設計網站的時候確實是有需要，但是你貼的內容有點不太明確（這張圖是說那個連結預覽的卡片可以是 Compact 橫式、也可以是延展直式的），這個也許可以透過 https://github.com/TeaMeow/TocasUI/issues/601 水平卡片（Horizontal Card）完成。

![image](https://user-images.githubusercontent.com/7308718/56670614-be6eff00-66e5-11e9-88a7-ece0bd12cedf.png)

**Comment by goodjack** [comment]
其實我的意思只是可以讓圖片指定在左側
應該是重複了 #601 沒錯 😅
