### ISSUE TITLE
以自訂的內容排序表格

### ISSUE THREAD

**Issue by oToToT** [teacat/tocas#747]
如題，希望表格的有某種方式可以自由的選擇該如何排序，例如我可以標明我現在這個column的內容都是數字的話，那排序的方式可以把他們當作數值排序，而不是以原本的字典序來排序

**Comment by YamiOdymel** [comment]
可能跟 [Table 无法根据数据类型排列](https://github.com/TeaMeow/TocasUI/issues/572) 有關？

**Comment by oToToT** [comment]
是的，抱歉前面搜尋的時候沒注意到
