### ISSUE TITLE
妥善地支援亮色與 Inverted 反色主題

### ISSUE THREAD

**Issue by YamiOdymel** [teacat/tocas#758]
由於 https://github.com/TeaMeow/TocasUI/issues/757 的緣故，Tocas UI 應該要妥善地支援 Inverted 色系，這個色系在亮色主題時，會呈現黑色，而暗色主題時這個色系會呈現白色。

簡單來說 Inverted 就是「與目前色系相反」的一個神奇蹦蹦好顏色。

透過 Tocas UI 3 的動態色系表應該不難達到。

**Comment by gnehs** [comment]
有打算支援全域蹦蹦暗色主題嗎
