### ISSUE TITLE
sidebar closable not work

### ISSUE THREAD

**Issue by city8208** [teacat/tocas#778]
這幾天
發現 "側邊欄" 在開啟時點擊右邊主視窗會自動關掉

但是我有明確填入設定
        ts('.left.inverted.sidebar').sidebar({
            closable: true
        }).sidebar('show');

對應物件
    <div class="ts wide left big sidebar inverted vertical menu"  ......

許久沒有麻煩你了,也期待3.0版(現在Nodejs上的版本不知道是不是你的)

**Comment by YamiOdymel** [comment]
有點久沒維護 2.2 版本了，但是 `closable: true` 的話就是表示說側邊欄出現時，可以透過點擊主畫面區域來自動關閉側邊欄。

如果你的側邊欄是常駐型的，這個功能應該要設為 `false`，然後自行加上一個按鈕會在被按下時書叫 `ts('.sidebar').sidebar('hide')`。

最近都在研究 Tocas 4.0（3.0 因為某些 Alpha 大亂鬥的原因名字被搞到太複雜了）

**Comment by city8208** [comment]
抱歉這部分貼錯
（原本打false的）
但仍沒有成功

不知你那邊測試是否正常

另外2.3這個想問大概會放到什麼時候
（怕關掉）
因為目前下載下來用的css
無法下載icon

**Comment by YamiOdymel** [comment]
如果試著把 `.sidebar` 加上 `static visible` 然後不要使用 `.sidebar('show')` 呢？

**Comment by city8208** [comment]
> 如果試著把 `.sidebar` 加上 `static visible` 然後不要使用 `.sidebar('show')` 呢？

目前該介面是要做到縮放的
另外直接去執行remove或add
之後很容易產生問題
比較非正規的解決方式XD
