### ISSUE TITLE
清單連結在滑鼠 hover 時，圖示和文字的變色相反

### ISSUE THREAD

**Issue by goodjack** [teacat/tocas#780]
發現清單連結在滑鼠 hover 時，圖示和文字的變色相反

滑鼠指上去前
![滑鼠指上去前 image](https://user-images.githubusercontent.com/1116129/82123080-f867e300-97c9-11ea-8c53-9af3ddc1d2a6.png)
滑鼠指上去後
![滑鼠指上去後 image](https://user-images.githubusercontent.com/1116129/82123091-0453a500-97ca-11ea-9301-f15cdc71dd9c.png)

```html
<div class="ts link list">
    <a class="item">
        <i class="help icon"></i> 浮動圖示
    </a>
</div>
```

[遊樂場連結](https://tocas-ui.com/try/?html=%3Cdiv%20class=%22ts%20link%20list%22%3E%5Cn%20%20%20%20%3Ca%20class=%22item%22%3E%5Cn%20%20%20%20%20%20%20%20%3Ci%20class=%22help%20icon%22%3E%3C/i%3E%20%E6%B5%AE%E5%8B%95%E5%9C%96%E7%A4%BA%5Cn%20%20%20%20%3C/a%3E%5Cn%3C/div%3E)

---

發現所有 issue 都關掉了 😢
一切還好嗎？

**Comment by YamiOdymel** [comment]
因為在處理 4.0 的事情，所以這個星期花了點時間把那堆 700 多個 Issue 看過之後總結一些功能，然後全部關掉了，不然思緒會有點亂 🌚

**Comment by goodjack** [comment]
嚇我一跳
剛剛急忙 mirror clone 了一下 😅
