### ISSUE TITLE
CDNJS中呈現404

### ISSUE THREAD

**Issue by cytsai1008** [teacat/tocas#789]
如圖所示
另外在Readme中的CDNJS連結也會回傳404
本人在localhost中測試透過CDN載入TOCAS時Console對於CDN部分回傳了 `X-Content-Type-Options: nosniff`
還請麻煩儘速修復

![Screenshot_20220414-012613_Chrome.png](https://user-images.githubusercontent.com/47322522/163236618-dc246ee5-a445-41b3-8dad-2f7c2f60bf1a.png)

**Comment by YamiOdymel** [comment]
原本是在等 CDNJS 發佈，結果他們一直沒更新。

把網址裡的 `/tocas/` 改成 `/tocas-ui/` 就可以使用了，

我會先把文件裡都先改成 `tocas-ui`

等他們正式推送我再把網址改成 `tocas` 好了
