### ISSUE TITLE
在Firefox (Developer Edition)與Chrome中同一份Code存在部分差異

### ISSUE THREAD

**Issue by cytsai1008** [teacat/tocas#790]
如圖所示
在Firefox與Chrome的寬度不同
P.S. 我尚未測試過Firefox Stable是否也有此差異
大小部份我是使用 `is-fluid`
下拉清單我是使用 `ts-select is-large is-underlined`
另外下拉清單有白邊
如有需要我能提供部分Source Code

![aaa2](https://user-images.githubusercontent.com/47322522/163378576-f10ef45a-83e6-429a-9473-135c1cb2f3b1.png)

**Comment by YamiOdymel** [comment]
不同寬度的問題可能是父容器沒有指定固定寬度，而不同的表單欄位在不同瀏覽器上會有部份的不同表現方式而有所影響。

可以在父容器中加上固定寬度（如：[登入頁面範例](https://v4.tocas-ui.com/zh-tw/examples/login.html)）解決這個系統先天性的渲染問題。

---

4e5cd018cd3b8f93bdf87c9664649a23d433e0d2 下拉式選單的白邊在 Firefox 上是因為選單沒有好好地繼承背景顏色，修正了
