### ISSUE TITLE
修正错字和Localization

### ISSUE THREAD

**Issue by ebiggerr** [teacat/tocas#796]
你好，我在浏览文档和范例时有发现存在一些错字。对于Localization的方面，也想贡献小小的帮助。

![image](https://user-images.githubusercontent.com/46164655/163660563-59ac84f3-70f6-4c7d-87b3-9ffbf6c03ea3.png)

如果得到允许的话，我再来开PR。 谢谢。

**Comment by YamiOdymel** [comment]
英文的語系目前其實是有 90% 的機率要翻新重弄，

那只是當初測試時先用 [DeepL](https://www.deepl.com/translator) 臨時蓋出來的翻譯

我不建議你花費心思在那上面 👀

我打算之後如果有要推廣到 Reddit 或是國外論壇的話，才會抽空更新相關的翻譯
