### ISSUE TITLE
范例页面里的截图，对网页加载不友善。

### ISSUE THREAD

**Issue by ebiggerr** [teacat/tocas#797]
列举， `/zh-tw/examples.html` 里的截图目前是 `1081x1032`的resolution。如果没有特别的需求的话，`/zh-tw/examples.html` 可以引用较低resolution(640x367)的截图来显示。

两种resolution
`examples/screenshots/blog_dark.png` (1081x1032)
`examples/screenshots/blog_dark_thumbnail.png`  (640x367)

**Comment by YamiOdymel** [comment]
我其實也有考慮過用 `srcset` 來響應式載入不同圖片大小，只是覺得我網路跑得蠻快的就略過那個步驟了

最近如果有時間的話，再來更新小尺寸的圖片
