### ISSUE TITLE
ts-text is-link 的 selector 中 `.is-link` 重複了 3 遍

### ISSUE THREAD

**Issue by t510599** [teacat/tocas#811]
https://github.com/teacat/tocas/blob/85be601fcab454586332e7c6014c8cd22f342039/src/text.css#L107-L109

如標題所述，`.is-link` 重複了 3 遍，導致自己在覆寫顏色設定時，要用更高 specificity 的 selector 才蓋的掉。
好奇有什麼特別的原因，才會需要像這樣設計 selector ?

**Comment by YamiOdymel** [comment]
我建議覆蓋 Tocas UI 樣式的時候都用  `!important` （至少我是都這樣啦）

我記得沒錯的話那個樣式是要覆蓋 `reboot.css` 裡面[預設針對連結顏色更改的樣式](https://github.com/teacat/tocas/blob/master/src/reboot.css#L100)

```css
[class*="ts-"] a {
    color: inherit;
}
```

**Comment by YamiOdymel** [comment]
為什麼你的內容可以張貼程式碼預覽 🤔

**Comment by t510599** [comment]
好的了解，感謝回覆。

會需要覆蓋的原因主要是 `is-link` 在 `is-tertiary` 的 content 中實在不太明顯 (與 #810 相似)
![image](https://user-images.githubusercontent.com/18533304/166946304-3d876ff4-9cc2-421a-a3e6-1e5162d805b4.png)

另外程式碼預覽的部分，只要先點擊行數，點選選單中的 permalink 並貼到 issue 即可。
![image](https://user-images.githubusercontent.com/18533304/166945814-8ef96530-5999-484b-845b-906751f874a6.png)

**Comment by YamiOdymel** [comment]
暗黑色系的連結顏色應該要改的更亮一點，我之前是有想要研究過，我再來看看 🤔

**Comment by YamiOdymel** [comment]
關閉，轉到 #812
