### ISSUE TITLE
input type="month" 顯示寬度在 Firefox 與 Edge 上不同

### ISSUE THREAD

**Issue by secret715** [teacat/tocas#813]
input type="month" 顯示寬度在 Firefox 與 Edge 上不同
Firefox 會很長，Edge就是顯示剛好日期的寬度，可能跟 Firefox 不支援 input type="month" 有關係？

**Firefox**
![圖片](https://user-images.githubusercontent.com/3306134/166959317-65fd24e7-5790-4b23-9ead-79bfa00d37f4.png)

**Edge**
![圖片](https://user-images.githubusercontent.com/3306134/166959112-88042a6e-8098-4c33-af75-606131fee2ce.png)

**Comment by YamiOdymel** [comment]
我之前有試過幾個 Input 在 Firefox 上確實會變得很寬，

但…怎麼說，好像又不適合預設給他一個寬度，畢竟每個人要的預設寬度都不太一樣

我還真沒意識到 Firefox 不支援 `type="month"` 的 Input，

我會建議你用一個有固定寬度的容器把他包起來
（或是乾脆直接固定他的寬度啦— 🤔）

Bootstrap 解決這個問題的辦法是直接把每個 Input 都變成 100% 寬度填滿整行
（也對，這樣的話根本就不用關心不同寬度的問題了）

---

還是我應該直接依照 Chrome 給他一個預設的寬度算了 👀

**Comment by YamiOdymel** [comment]
每個瀏覽器預設的寬度都不一樣，又不能改預設值 😭

即便是在 Chrome 上，Text Input 跟 Date Input 的寬度也有可能不同。
預設替 `input` 指定一個 `width` 寬度看起來不是好作法，
因為這會讓 Input 沒辦法隨著父容器自動變更其寬度。

目前先不做處理，但如果下次還有人意識到相同的問題，
可能會將 Input 全面改寫為 `width: 100%`（或是某個版本開始會這麼做）

用以強迫使用者設計時必須自行以 網格系統 或是 手動指定 來縮限 Input 的寬度，
避免有人太仰賴瀏覽器預設的寬度而重現這個問題 🥺
