### ISSUE TITLE
tocas-4.0 有支援 dropdown 嗎

### ISSUE THREAD

**Issue by ChiaYuSu** [teacat/tocas#815]
如題
想請問最新版本的 tocas-ui 有沒有支援 multiple-dropdown

**Comment by YamiOdymel** [comment]
沒有，類似的內容在「[減少 JavaScript 模組的干涉](https://v4.tocas-ui.com/zh-tw/getting-started.html#modules)」章節有稍微提及。

因為現在前端有太多不同框架，如果需要下拉式選單的話可以參考以 Menu 作為[基礎的選單](https://v4.tocas-ui.com/zh-tw/menu.html#dropdown)，

自行實作 JavaScript 的部份之後重複使用。

![image](https://user-images.githubusercontent.com/7308718/168417718-fcb6e780-768e-477a-be2b-75658a2a3578.png)
