### ISSUE TITLE
Document中藍色反白部分與Windows預設反白色彩過於接近

### ISSUE THREAD

**Issue by cytsai1008** [teacat/tocas#816]
如圖，這樣可能造成反白時可讀性下降並且在複製時難以確認是否有漏字
也許可以調暗背景色彩？
![image](https://user-images.githubusercontent.com/47322522/169635258-c0e5b0a2-5178-454c-8820-aa14618be3cc.png)

**Comment by YamiOdymel** [comment]
今天會更新文件，改前

![sshot-2022-05-21-7](https://user-images.githubusercontent.com/7308718/169639271-d5d0f431-06eb-4c63-8052-1e093d4fc9b9.png)
![sshot-2022-05-21-8](https://user-images.githubusercontent.com/7308718/169639272-8b9ff963-efcb-4b60-a763-bbacd19906a9.png)

改後

![sshot-2022-05-21-6](https://user-images.githubusercontent.com/7308718/169639270-98630f04-70af-4293-b83b-27d0712189fa.png)
![sshot-2022-05-21-5](https://user-images.githubusercontent.com/7308718/169639269-4f416cb6-ff5e-44ee-ab20-f42ef015592c.png)

**Comment by YamiOdymel** [comment]
Tocas 4.0.4 釋出了但是 CDNJS 還沒更新，看起來文件要明天才能更新了 😭👌
