### ISSUE TITLE
Missed the concert of accessibility

### ISSUE THREAD

**Issue by kayac-chang** [teacat/tocas#838]
The global marketing still need to support Accessibility (A11y) for most of the countries
especially US and Europe need to pass WCAG depends on law.

Please consider improve the accessibility.

Check your website
https://wave.webaim.org/report#/https://v4.tocas-ui.com/zh-tw/index.html

See also
https://developer.mozilla.org/en-US/docs/Web/Accessibility
https://getbootstrap.com/docs/5.1/getting-started/accessibility/

**Comment by YamiOdymel** [comment]
lmao major Errors are seems to be fixed easily, but how do I fix the Contrast Error if CSS doesn't provide the dynamic foreground color based on the background color 

I'm literally crying 😭👌

![image](https://user-images.githubusercontent.com/7308718/179649472-fee917c8-db9f-458e-804b-c820fd6ac493.png)

**Comment by YamiOdymel** [comment]
Mark as wontfix but there's still chance to fix it 🫠 just not sure when.

It's hard to achieve due to the examples are dynamic colors, and most of the websites don't meet the A11y requirements. Maybe reopen when someone is facing the legal issues.
