### ISSUE TITLE
新增 <datalist> 範例

### ISSUE THREAD

**Issue by YamiOdymel** [teacat/tocas#843]
![image](https://user-images.githubusercontent.com/7308718/192128817-8bd8431f-4a58-4703-a390-c56bc28f939a.png)

**Comment by YamiOdymel** [comment]
想了想覺得 Tocas 不是 W3School

**Comment by goodjack** [comment]
但 Tocas 會不會有特殊樣式或用法？

**Comment by YamiOdymel** [comment]
試了一下是系統原生的樣式，所以用法跟外觀沒差別
