### ISSUE TITLE
文件的「界限容器」的頁面格式與其他頁面不同

### ISSUE THREAD

**Issue by LianSheng197** [teacat/tocas#873]
文件的「界限容器」的頁面不包含左側跟右側選單
https://v4.tocas-ui.com/zh-tw/container.html

其他頁面都有左側跟右側選單（左側的「初入上手」與右側的「外觀」）
![image](https://user-images.githubusercontent.com/18535495/205675275-e87c98cc-34b2-4c20-aa2e-0bdaf1e3506a.png)

而「界限容器」頁面看起來更像是一個獨立的頁面
![image](https://user-images.githubusercontent.com/18535495/205675588-a2411ecd-248d-43dc-9ea8-3c2a02938e0f.png)

不曉得是特殊考量還是單純疏漏？

**Comment by LianSheng197** [comment]
另外，在英文語系的「Container」頁面也是如此。
https://v4.tocas-ui.com/en-us/container.html

**Comment by YamiOdymel** [comment]
漏看了這個 Issue，主要是因為 Container 的 Demo 需要有足夠寬的空間，才比較能看得出來各個之間的寬度差異。

加上左右側選單的話，基本上會頂到寬度限制導致看起來都一樣。以前 [v2 的 Container](https://v2.tocas-ui.com/elements/container/) 設計也是長這樣就是了。

**Comment by YamiOdymel** [comment]
其實最初這個設計方式是跟 [Semantic UI 的 Container](https://semantic-ui.com/elements/container.html) 學來的。

一般的按鈕介紹頁面：

![image](https://user-images.githubusercontent.com/7308718/206883942-2ad9f789-0271-4cd5-87dd-cd34ed4cf591.png)

容器的介紹頁面：

![image](https://user-images.githubusercontent.com/7308718/206883939-b9c8ab43-16d9-488c-a74b-33b119e083c1.png)

差別在於 Tocas UI 沒加可以開關切換的側邊選單就是了，有點小麻煩。

所以現在需要人工去戳上一頁，感謝您的配合 🥺

**Comment by LianSheng197** [comment]
:sob: 好吧
