### ISSUE TITLE
關於@tocas/dist/tocas.min.js檔案為空的問題

### ISSUE THREAD

**Issue by dase1353** [teacat/tocas#898]
您好
我使用Angular，用npm安裝了tocas
但是經過檢查
@tocas/dist/tocas.min.js這的檔案似乎是空的?

想詢問一下這的檔案實際的作用是?

**Comment by YamiOdymel** [comment]
下一個更新才會在裡面擺放 JavaScript 程式碼，有 Dropdown, Tab, Tooltip 等

**Comment by dase1353** [comment]
好的感謝，我先把它拿掉。
因為angular要ng build或serve會出錯表示這檔案沒東西
