### ISSUE TITLE
Angular App-layout App-topbar 組合的問題

### ISSUE THREAD

**Issue by dase1353** [teacat/tocas#908]
```html
<div class="ts-app-layout is-vertical is-full">
  <div class="cell">
    <div class="ts-app-topbar">
      <div class="start">
        <a class="item">
          <span class="ts-icon is-bars-icon"></span>
        </a>
        <div class="item is-text" routerLink="">功能測試</div>
      </div>
      <div class="center">
        <!-- <marquee style="color: white;">傳說在天上有塊封神榜</marquee> -->
        <!-- <div class="item is-text">功能測試</div> -->
        <!-- <a class="item">
          <span class="ts-icon is-magnifying-glass-icon"></span>
        </a> -->
      </div>
      <div class="end">
        <a class="item">
          <span class="ts-icon is-magnifying-glass-icon"></span>
        </a>
        <a class="item">
          <span class="ts-icon is-ellipsis-vertical-icon"></span>
        </a>
      </div>
    </div>
  </div>
  <div class="cell is-fluid">
    <router-outlet></router-outlet>
  </div>
</div>
```
稍微詢問一點問題
Angular 內混搭 App-layout App-topbar 如上所示
在<div class="center">中
有跑馬燈 純文字項目 跟一個ICON
![image](https://user-images.githubusercontent.com/46934514/228859455-c7ac1a78-e467-42d0-9fcf-a0d51e9ae118.png)

可以看到純文字項目似乎會被切掉頂端一小部分
不過我看官網的範本好像沒這個問題..所以想問一下是不是用法有誤

**Comment by YamiOdymel** [comment]
真神奇，你是用什麼瀏覽器跟作業系統（和螢幕是不是有 HiDPI 高解析度設定，例如 MacBook Retina？）？

看起來應該是不同電腦上的渲染問題，你可以試試看

```
<div class="item is-text" style="margin: 0;">我的相簿</div>
```

透過指定 `margin: 0` 來看看問題會不會改善，如果有的話下個更新會修正（又或者有時候瀏覽器他自己更新之後就好了），

然後我不確定 `<marquee>` 能不能如期運作，因為 [`<marquee>` 被廢棄很久](https://developer.mozilla.org/zh-TW/docs/Web/HTML/Element/marquee)了

**Comment by dase1353** [comment]
WIN11 微軟的EDGE
家裡電腦重灌之後，就懶得灌Chrome了，發現EDGE超好用
Chrome我有空測試一下
EDGE測試完是有恢復正常了
![image](https://user-images.githubusercontent.com/46934514/228893832-0cea2416-440c-4823-b6cf-e9f8d5a21f03.png)

**Comment by dase1353** [comment]
上面EDGE，下面CHROME
WIN11 2K螢幕跟21:9兩種螢幕都會發生
圖一修正前
![image](https://user-images.githubusercontent.com/46934514/228899637-f2d974a8-457b-4ca0-b8fb-9299a1f204ef.png)
圖二修正後
![image](https://user-images.githubusercontent.com/46934514/228899784-07ced8b1-cc79-4e51-a05e-185baa6d615b.png)
