### ISSUE TITLE
廢除 Space 元件

### ISSUE THREAD

**Issue by YamiOdymel** [teacat/tocas#914]
新的 Spaced Utilities 如 `u-top-spaced-large` 可以取代原本的 `.ts-space.is-large`

**Comment by PichuChen** [comment]
在 4.2.5 之後 https://github.com/teacat/tocas/issues/935 請使用 `has-top-spaced-large` 而不是 `u-top-spaced-large` 另外 `u-top-spaced-large` 系列的行為和 `ts-space` 不同，因此不能直接取代

**Comment by YamiOdymel** [comment]
因為後續有一些更改，所以文件沒有即時更新到之間的關聯性

`.ts-space` 被移除的原因是因為他們為了在視覺上增加空白，而導致 HTML 結構有太多不必要的 `.ts-space`

如果需要使用 `ts-space` 最簡單的方式是 `<div class="has-top-spaced"></div>`

另一個方式可以考慮 `.ts-wrap` 或直接在某些元素使用 `has-top-spaced`

**Comment by PichuChen** [comment]
補充一下應該是在下面的元素加上 `has-top-spaced` 的 CSS 屬性如果是最後一個元素了那就改在上一個元素加上 `has-bottom-spaced` 具體而言就是參考[這邊](https://github.com/teacat/tocas/blob/0bb185e666d74a3925df78386e31abcfaed4cec1/src/utilities.css#L242)的程式碼使用

另外這個作法無法替代
```
<div class="ts-space is-large"></div>
<div class="ts-space is-large"></div>
<div class="ts-space is-large"></div>
```

來產生一片空白的寫法，不過如果需要這樣產生一片空白的話，有可能是哪邊設計的有問題就是了...?
