### ISSUE TITLE
「評分(Rating)」在 Firefox 瀏覽器上似乎無法正常顯示顏色 :/

### ISSUE THREAD

**Issue by Alpaca0x0** [teacat/tocas#924]
![image](https://github.com/teacat/tocas/assets/58300460/eb93c4e7-5403-483b-9a34-f266c9b9667a)

加了顏色的也是無法顯示

![image](https://github.com/teacat/tocas/assets/58300460/203c5fbb-6ef4-43f6-8510-fd5c55d9a6fa)

但是半顆星的卻可以顯示

![image](https://github.com/teacat/tocas/assets/58300460/f1a37711-12a3-4fa8-b0c1-d2be978758c0)

**Comment by YamiOdymel** [comment]
什麼 Firefox 版本 🤔

**Comment by YamiOdymel** [comment]
找到 Bug 了，因為 Rating 有使用到 ":has()" 選擇器（而 Firefox 還沒支援），

那個 `.is-active` 的樣式剛好與 `:has` 整合在同個 Selector，所以 Firefox 直接拋棄掉整個條件。

```
.ts-rating :is(.star,.heart).is-active, .ts-rating.is-input :is(.star,.heart):checked,
.ts-rating.is-input :is(.star,.heart):has(~:is(.star,.heart):checked),
.ts-rating.is-input :is(.star,.heart):has(~:is(.star,.heart):hover),
.ts-rating.is-input :is(.star,.heart):hover
```

**Comment by YamiOdymel** [comment]
目前能做的修正就是把 `.is-active` 獨立出來自己一行條件，但你目前需要先用下列樣式修正

```
.ts-rating :is(.star,.heart).is-active,
.ts-rating.is-input :is(.star,.heart):checked {
    color: var(--color);
}
```

**Comment by Alpaca0x0** [comment]
暫時添加上這幾段 CSS，目前正常運作了，感謝您。
