### ISSUE TITLE
[T2] Bug - 圖片無法水平置中

### ISSUE THREAD

**Issue by kahogeoff** [teacat/tocas#93]
![tocas ui](https://cloud.githubusercontent.com/assets/843571/18658700/d33b36bc-7f37-11e6-9a95-6d301a56c0d1.png)
使用Chrome 53看到的畫面，可以看到圖片並非水平置中。

將

``` html
<img class="ts small centered image" src="..">
```

修改為

``` html
<img class="ts small centered image" src=".." style="display: block">
```

之後可正常顯示。

**Comment by YamiOdymel** [comment]
把 `.centered` 的 `image` 從 `inline-block` 改成了 `block`，

不過 `centered images` 的部分還沒解決，暫時想不到應該怎麼處置
_（例如說應該是 `images` 這個容器該置中 還是 `images` 跟裡面的 `image` 都要置中 之類的）_

文件等一下就會更新了，順便也替一些未完成的元素加上了「未完成」的標籤，

謝謝你詳細的資訊 :D
