### ISSUE TITLE
Range Input

### ISSUE THREAD

**Issue by YamiOdymel** [teacat/tocas#941]
以前 Tocas 2.x 的時候有，沒想到 Tocas 4.x 竟然忘記這個東西了。當然，最好還是依照 HTML 去做

![image](https://github.com/teacat/tocas/assets/7308718/4522d40c-2904-491f-86e9-56b424515f8e)

https://m3.material.io/components/sliders/overview

https://m2.material.io/components/sliders

**Comment by LianSheng197** [comment]
最近使用時把整個元件樣式翻爛都找不到這玩意...

我需要這個酷酷的東西 👀

**Comment by YamiOdymel** [comment]
用 JavaScript 會複雜化，而且很難跟現有的 Vue, React 這種雙向綁定工具一起運作，所以先實作了基本的 `<input type="range">`
