### ISSUE TITLE
App Topbar 文字底部在 firefox 上被切掉

### ISSUE THREAD

**Issue by james58899** [teacat/tocas#948]
https://v4.tocas-ui.com/zh-tw/app-topbar.html

![](https://github.com/teacat/tocas/assets/5798637/5452a6f3-0516-42db-acc2-06c1efed4185)
![](https://github.com/teacat/tocas/assets/5798637/bef93385-1b25-4547-a836-79b25177183a)

**Comment by YamiOdymel** [comment]
#908 修過了這又什麼鬼

**Comment by james58899** [comment]
如果改成 `display: inline-block` 或者把 `.ts-app-topbar` 的 `line-height` 刪掉就好了

**Comment by YamiOdymel** [comment]
或是改用 Chrome
