### ISSUE TITLE
Modal 中的 Tooltip 被壓在 Modal 下面

### ISSUE THREAD

**Issue by lekoOwO** [teacat/tocas#953]
As title，對 Modal 中的元素附加 Tooltip，Tooltip 並不會浮在 Modal(或其子元素) 上，導致 Tooltip 看不到。

**Comment by YamiOdymel** [comment]
之後有考慮過 #946 改用 `<dialog>` 的 HTML 標籤，這個標籤預設解決了 z-index 的問題

筆記：Popover API

https://tzulinchang.medium.com/html-popover-688619c3a934
